// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_CategoryType.h"

@implementation Shopping_CategoryType

@synthesize categoryID = _categoryID;
@synthesize categoryLevel = _categoryLevel;
@synthesize categoryName = _categoryName;
@synthesize categoryParentID = _categoryParentID;
@synthesize categoryParentName = _categoryParentName;
@synthesize itemCount = _itemCount;
@synthesize categoryNamePath = _categoryNamePath;
@synthesize categoryIDPath = _categoryIDPath;
@synthesize leafCategory = _leafCategory;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CategoryID" propertyName:@"categoryID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"categoryID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CategoryLevel" propertyName:@"categoryLevel" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"categoryLevel"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CategoryName" propertyName:@"categoryName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"categoryName"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CategoryParentID" propertyName:@"categoryParentID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"categoryParentID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CategoryParentName" propertyName:@"categoryParentName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"categoryParentName"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ItemCount" propertyName:@"itemCount" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"itemCount"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CategoryNamePath" propertyName:@"categoryNamePath" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"categoryNamePath"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CategoryIDPath" propertyName:@"categoryIDPath" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"categoryIDPath"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LeafCategory" propertyName:@"leafCategory" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"leafCategory"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}



-(void)dealloc {
    self.categoryID = nil;
    self.categoryLevel = nil;
    self.categoryName = nil;
    self.categoryParentID = nil;
    self.categoryParentName = nil;
    self.itemCount = nil;
    self.categoryNamePath = nil;
    self.categoryIDPath = nil;
    self.leafCategory = nil;
    self.any = nil;
}

@end
