// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_FindReviewsAndGuidesRequestType.h"
#import "Shopping_ProductIDType.h"

@implementation Shopping_FindReviewsAndGuidesRequestType

@synthesize productID = _productID;
@synthesize userID = _userID;
@synthesize categoryID = _categoryID;
@synthesize maxResultsPerPage = _maxResultsPerPage;
@synthesize pageNumber = _pageNumber;
@synthesize reviewSort = _reviewSort;
@synthesize sortOrder = _sortOrder;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"FindReviewsAndGuidesRequest" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ProductID" propertyName:@"productID" type:PICO_TYPE_OBJECT clazz:[Shopping_ProductIDType class]];
    [map setObject:ps forKey:@"productID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserID" propertyName:@"userID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"userID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CategoryID" propertyName:@"categoryID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"categoryID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaxResultsPerPage" propertyName:@"maxResultsPerPage" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"maxResultsPerPage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PageNumber" propertyName:@"pageNumber" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"pageNumber"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ReviewSort" propertyName:@"reviewSort" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"reviewSort"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SortOrder" propertyName:@"sortOrder" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"sortOrder"];
    
    return map;
}



-(void)dealloc {
    self.productID = nil;
    self.userID = nil;
    self.categoryID = nil;
    self.maxResultsPerPage = nil;
    self.pageNumber = nil;
    self.reviewSort = nil;
    self.sortOrder = nil;
}

@end
