// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_FindPopularSearchesRequestType.h"

@implementation Shopping_FindPopularSearchesRequestType

@synthesize categoryID = _categoryID;
@synthesize queryKeywords = _queryKeywords;
@synthesize maxKeywords = _maxKeywords;
@synthesize maxResultsPerPage = _maxResultsPerPage;
@synthesize pageNumber = _pageNumber;
@synthesize includeChildCategories = _includeChildCategories;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"FindPopularSearchesRequest" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"CategoryID" propertyName:@"categoryID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"categoryID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"QueryKeywords" propertyName:@"queryKeywords" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"queryKeywords"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaxKeywords" propertyName:@"maxKeywords" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"maxKeywords"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MaxResultsPerPage" propertyName:@"maxResultsPerPage" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"maxResultsPerPage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PageNumber" propertyName:@"pageNumber" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"pageNumber"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IncludeChildCategories" propertyName:@"includeChildCategories" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"includeChildCategories"];
    
    return map;
}



-(void)dealloc {
    self.categoryID = nil;
    self.queryKeywords = nil;
    self.maxKeywords = nil;
    self.maxResultsPerPage = nil;
    self.pageNumber = nil;
    self.includeChildCategories = nil;
}

@end
