// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Shopping_ItemCompatibilityType;

/**
 
 A list of compatible applications specified as name and value pairs. Describes assemblies with which a part is compatible (i.e., compatibility by application). For example, to specify a part's compatibility with a vehicle, the name would map to standard vehicle characteristics (e.g., Year, Make, Model, Trim, and Engine). The values describe the specific vehicle, such as a 2006 Honda Accord.
 <br><br>
 Parts Compatibility is supported in limited Parts & Accessories categories, on the eBay Motors (US) site (site ID 100) only.
 
 
 @ingroup ShoppingInterface
*/
@interface Shopping_ItemCompatibilityListType : NSObject <PicoBindable> {

@private
    NSMutableArray *_compatibility;
    NSMutableArray *_any;

}


/**
 
 Contains details for an individual compatible application, consisting of a list of name-value pairs and related compatibility notes. 
 <br><br>
 Parts Compatibility is supported in limited Parts & Accessories categories, on the eBay Motors (US) site (site ID 100) only.
 
 
 entry type : class Shopping_ItemCompatibilityType
*/

@property (nonatomic, retain) NSMutableArray *compatibility;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;


@end
