// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Shopping_CountryCodeType.h"

/**
 @file
 
 This enumerated type contains a partial list of ISO 3166 standard two-letter codes that represent countries around the world.
 <br><br>
 It is recommended that users use the <b>GeteBayDetails</b> call of the Trading API to see the full list of currently supported country codes,
 and the English names associated with each code (e.g., KY="Cayman Islands"). Call 
 <b>GeteBayDetails</b> with <b>DetailName</b> set to <b>Country</b>, and then look for <b>CountryDetails.Country</b> fields in the response.
 
*/

/**
 
 Afghanistan.
 
*/
NSString *const Shopping_CountryCodeType_AF = @"AF";

/**
 
 Albania.
 
*/
NSString *const Shopping_CountryCodeType_AL = @"AL";

/**
 
 Algeria.
 
*/
NSString *const Shopping_CountryCodeType_DZ = @"DZ";

/**
 
 American Samoa.
 
*/
NSString *const Shopping_CountryCodeType_AS = @"AS";

/**
 
 Andorra.
 
*/
NSString *const Shopping_CountryCodeType_AD = @"AD";

/**
 
 Angola.
 
*/
NSString *const Shopping_CountryCodeType_AO = @"AO";

/**
 
 Anguilla.
 
*/
NSString *const Shopping_CountryCodeType_AI = @"AI";

/**
 
 Antarctica.
 
*/
NSString *const Shopping_CountryCodeType_AQ = @"AQ";

/**
 
 Antigua and Barbuda.
 
*/
NSString *const Shopping_CountryCodeType_AG = @"AG";

/**
 
 Argentina.
 
*/
NSString *const Shopping_CountryCodeType_AR = @"AR";

/**
 
 Armenia.
 
*/
NSString *const Shopping_CountryCodeType_AM = @"AM";

/**
 
 Aruba.
 
*/
NSString *const Shopping_CountryCodeType_AW = @"AW";

/**
 
 Australia.
 
*/
NSString *const Shopping_CountryCodeType_AU = @"AU";

/**
 
 Austria.
 
*/
NSString *const Shopping_CountryCodeType_AT = @"AT";

/**
 
 Azerbaijan.
 
*/
NSString *const Shopping_CountryCodeType_AZ = @"AZ";

/**
 
 Bahamas.
 
*/
NSString *const Shopping_CountryCodeType_BS = @"BS";

/**
 
 Bahrain.
 
*/
NSString *const Shopping_CountryCodeType_BH = @"BH";

/**
 
 Bangladesh.
 
*/
NSString *const Shopping_CountryCodeType_BD = @"BD";

/**
 
 Barbados.
 
*/
NSString *const Shopping_CountryCodeType_BB = @"BB";

/**
 
 Belarus.
 
*/
NSString *const Shopping_CountryCodeType_BY = @"BY";

/**
 
 Belgium.
 
*/
NSString *const Shopping_CountryCodeType_BE = @"BE";

/**
 
 Belize.
 
*/
NSString *const Shopping_CountryCodeType_BZ = @"BZ";

/**
 
 Benin.
 
*/
NSString *const Shopping_CountryCodeType_BJ = @"BJ";

/**
 
 Bermuda.
 
*/
NSString *const Shopping_CountryCodeType_BM = @"BM";

/**
 
 Bhutan.
 
*/
NSString *const Shopping_CountryCodeType_BT = @"BT";

/**
 
 Bolivia.
 
*/
NSString *const Shopping_CountryCodeType_BO = @"BO";

/**
 
 Bosnia and Herzegovina.
 
*/
NSString *const Shopping_CountryCodeType_BA = @"BA";

/**
 
 Botswana.
 
*/
NSString *const Shopping_CountryCodeType_BW = @"BW";

/**
 
 Bouvet Island.
 
*/
NSString *const Shopping_CountryCodeType_BV = @"BV";

/**
 
 Brazil.
 
*/
NSString *const Shopping_CountryCodeType_BR = @"BR";

/**
 
 British Indian Ocean Territory.
 
*/
NSString *const Shopping_CountryCodeType_IO = @"IO";

/**
 
 Brunei Darussalam.
 
*/
NSString *const Shopping_CountryCodeType_BN = @"BN";

/**
 
 Bulgaria.
 
*/
NSString *const Shopping_CountryCodeType_BG = @"BG";

/**
 
 Burkina Faso.
 
*/
NSString *const Shopping_CountryCodeType_BF = @"BF";

/**
 
 Burundi.
 
*/
NSString *const Shopping_CountryCodeType_BI = @"BI";

/**
 
 Cambodia.
 
*/
NSString *const Shopping_CountryCodeType_KH = @"KH";

/**
 
 Cameroon.
 
*/
NSString *const Shopping_CountryCodeType_CM = @"CM";

/**
 
 Canada.
 
*/
NSString *const Shopping_CountryCodeType_CA = @"CA";

/**
 
 Cape Verde.
 
*/
NSString *const Shopping_CountryCodeType_CV = @"CV";

/**
 
 Cayman Islands.
 
*/
NSString *const Shopping_CountryCodeType_KY = @"KY";

/**
 
 Central African Republic.
 
*/
NSString *const Shopping_CountryCodeType_CF = @"CF";

/**
 
 Chad.
 
*/
NSString *const Shopping_CountryCodeType_TD = @"TD";

/**
 
 Chile.
 
*/
NSString *const Shopping_CountryCodeType_CL = @"CL";

/**
 
 China.
 
*/
NSString *const Shopping_CountryCodeType_CN = @"CN";

/**
 
 Christmas Island.
 
*/
NSString *const Shopping_CountryCodeType_CX = @"CX";

/**
 
 Cocos (Keeling) Islands.
 
*/
NSString *const Shopping_CountryCodeType_CC = @"CC";

/**
 
 Colombia.
 
*/
NSString *const Shopping_CountryCodeType_CO = @"CO";

/**
 
 Comoros.
 
*/
NSString *const Shopping_CountryCodeType_KM = @"KM";

/**
 
 Congo.
 
*/
NSString *const Shopping_CountryCodeType_CG = @"CG";

/**
 
 The Democratic Republic of the Congo.
 
*/
NSString *const Shopping_CountryCodeType_CD = @"CD";

/**
 
 Cook Islands.
 
*/
NSString *const Shopping_CountryCodeType_CK = @"CK";

/**
 
 Costa Rica.
 
*/
NSString *const Shopping_CountryCodeType_CR = @"CR";

/**
 
 Cote d'Ivoire.
 
*/
NSString *const Shopping_CountryCodeType_CI = @"CI";

/**
 
 Croatia.
 
*/
NSString *const Shopping_CountryCodeType_HR = @"HR";

/**
 
 Cuba.
 
*/
NSString *const Shopping_CountryCodeType_CU = @"CU";

/**
 
 Cyprus.
 
*/
NSString *const Shopping_CountryCodeType_CY = @"CY";

/**
 
 Czech Republic.
 
*/
NSString *const Shopping_CountryCodeType_CZ = @"CZ";

/**
 
 Denmark.
 
*/
NSString *const Shopping_CountryCodeType_DK = @"DK";

/**
 
 Djibouti.
 
*/
NSString *const Shopping_CountryCodeType_DJ = @"DJ";

/**
 
 Dominica.
 
*/
NSString *const Shopping_CountryCodeType_DM = @"DM";

/**
 
 Dominican Republic.
 
*/
NSString *const Shopping_CountryCodeType_DO = @"DO";

/**
 
 No longer in use.
 
*/
NSString *const Shopping_CountryCodeType_TP = @"TP";

/**
 
 Ecuador.
 
*/
NSString *const Shopping_CountryCodeType_EC = @"EC";

/**
 
 Egypt.
 
*/
NSString *const Shopping_CountryCodeType_EG = @"EG";

/**
 
 El Salvador.
 
*/
NSString *const Shopping_CountryCodeType_SV = @"SV";

/**
 
 Equatorial Guinea.
 
*/
NSString *const Shopping_CountryCodeType_GQ = @"GQ";

/**
 
 Eritrea.
 
*/
NSString *const Shopping_CountryCodeType_ER = @"ER";

/**
 
 Estonia.
 
*/
NSString *const Shopping_CountryCodeType_EE = @"EE";

/**
 
 Ethiopia.
 
*/
NSString *const Shopping_CountryCodeType_ET = @"ET";

/**
 
 Falkland Islands (Malvinas).
 
*/
NSString *const Shopping_CountryCodeType_FK = @"FK";

/**
 
 Faroe Islands.
 
*/
NSString *const Shopping_CountryCodeType_FO = @"FO";

/**
 
 Fiji.
 
*/
NSString *const Shopping_CountryCodeType_FJ = @"FJ";

/**
 
 Finland.
 
*/
NSString *const Shopping_CountryCodeType_FI = @"FI";

/**
 
 France.
 
*/
NSString *const Shopping_CountryCodeType_FR = @"FR";

/**
 
 French Guiana.
 
*/
NSString *const Shopping_CountryCodeType_GF = @"GF";

/**
 
 French Polynesia. Includes Tahiti.
 
*/
NSString *const Shopping_CountryCodeType_PF = @"PF";

/**
 
 French Southern Territories.
 
*/
NSString *const Shopping_CountryCodeType_TF = @"TF";

/**
 
 Gabon.
 
*/
NSString *const Shopping_CountryCodeType_GA = @"GA";

/**
 
 Gambia.
 
*/
NSString *const Shopping_CountryCodeType_GM = @"GM";

/**
 
 Georgia.
 
*/
NSString *const Shopping_CountryCodeType_GE = @"GE";

/**
 
 Germany.
 
*/
NSString *const Shopping_CountryCodeType_DE = @"DE";

/**
 
 Ghana.
 
*/
NSString *const Shopping_CountryCodeType_GH = @"GH";

/**
 
 Gibraltar.
 
*/
NSString *const Shopping_CountryCodeType_GI = @"GI";

/**
 
 Greece.
 
*/
NSString *const Shopping_CountryCodeType_GR = @"GR";

/**
 
 Greenland.
 
*/
NSString *const Shopping_CountryCodeType_GL = @"GL";

/**
 
 Grenada.
 
*/
NSString *const Shopping_CountryCodeType_GD = @"GD";

/**
 
 Guadeloupe.
 
*/
NSString *const Shopping_CountryCodeType_GP = @"GP";

/**
 
 Guam.
 
*/
NSString *const Shopping_CountryCodeType_GU = @"GU";

/**
 
 Guatemala.
 
*/
NSString *const Shopping_CountryCodeType_GT = @"GT";

/**
 
 Guinea.
 
*/
NSString *const Shopping_CountryCodeType_GN = @"GN";

/**
 
 Guinea-Bissau.
 
*/
NSString *const Shopping_CountryCodeType_GW = @"GW";

/**
 
 Guyana.
 
*/
NSString *const Shopping_CountryCodeType_GY = @"GY";

/**
 
 Haiti.
 
*/
NSString *const Shopping_CountryCodeType_HT = @"HT";

/**
 
 Heard Island and McDonald Islands.
 
*/
NSString *const Shopping_CountryCodeType_HM = @"HM";

/**
 
 Holy See (Vatican City state).
 
*/
NSString *const Shopping_CountryCodeType_VA = @"VA";

/**
 
 Honduras.
 
*/
NSString *const Shopping_CountryCodeType_HN = @"HN";

/**
 
 Hong Kong.
 
*/
NSString *const Shopping_CountryCodeType_HK = @"HK";

/**
 
 Hungary.
 
*/
NSString *const Shopping_CountryCodeType_HU = @"HU";

/**
 
 Iceland.
 
*/
NSString *const Shopping_CountryCodeType_IS = @"IS";

/**
 
 India.
 
*/
NSString *const Shopping_CountryCodeType_IN = @"IN";

/**
 
 Indonesia.
 
*/
NSString *const Shopping_CountryCodeType_ID = @"ID";

/**
 
 Islamic Republic of Iran.
 
*/
NSString *const Shopping_CountryCodeType_IR = @"IR";

/**
 
 Iraq.
 
*/
NSString *const Shopping_CountryCodeType_IQ = @"IQ";

/**
 
 Ireland.
 
*/
NSString *const Shopping_CountryCodeType_IE = @"IE";

/**
 
 Israel.
 
*/
NSString *const Shopping_CountryCodeType_IL = @"IL";

/**
 
 Italy.
 
*/
NSString *const Shopping_CountryCodeType_IT = @"IT";

/**
 
 Jamaica.
 
*/
NSString *const Shopping_CountryCodeType_JM = @"JM";

/**
 
 Japan.
 
*/
NSString *const Shopping_CountryCodeType_JP = @"JP";

/**
 
 Jordan.
 
*/
NSString *const Shopping_CountryCodeType_JO = @"JO";

/**
 
 Kazakhstan.
 
*/
NSString *const Shopping_CountryCodeType_KZ = @"KZ";

/**
 
 Kenya.
 
*/
NSString *const Shopping_CountryCodeType_KE = @"KE";

/**
 
 Kiribati.
 
*/
NSString *const Shopping_CountryCodeType_KI = @"KI";

/**
 
 Democratic People's Republic of Korea.
 
*/
NSString *const Shopping_CountryCodeType_KP = @"KP";

/**
 
 Republic of Korea.
 
*/
NSString *const Shopping_CountryCodeType_KR = @"KR";

/**
 
 Kuwait.
 
*/
NSString *const Shopping_CountryCodeType_KW = @"KW";

/**
 
 Kyrgyzstan.
 
*/
NSString *const Shopping_CountryCodeType_KG = @"KG";

/**
 
 Lao People's Democratic Republic.
 
*/
NSString *const Shopping_CountryCodeType_LA = @"LA";

/**
 
 Latvia.
 
*/
NSString *const Shopping_CountryCodeType_LV = @"LV";

/**
 
 Lebanon.
 
*/
NSString *const Shopping_CountryCodeType_LB = @"LB";

/**
 
 Lesotho.
 
*/
NSString *const Shopping_CountryCodeType_LS = @"LS";

/**
 
 Liberia.
 
*/
NSString *const Shopping_CountryCodeType_LR = @"LR";

/**
 
 Libyan Arab Jamahiriya.
 
*/
NSString *const Shopping_CountryCodeType_LY = @"LY";

/**
 
 Liechtenstein.
 
*/
NSString *const Shopping_CountryCodeType_LI = @"LI";

/**
 
 Lithuania.
 
*/
NSString *const Shopping_CountryCodeType_LT = @"LT";

/**
 
 Luxembourg.
 
*/
NSString *const Shopping_CountryCodeType_LU = @"LU";

/**
 
 Macao.
 
*/
NSString *const Shopping_CountryCodeType_MO = @"MO";

/**
 
 The Former Yugoslav Republic of Macedonia.
 
*/
NSString *const Shopping_CountryCodeType_MK = @"MK";

/**
 
 Madagascar.
 
*/
NSString *const Shopping_CountryCodeType_MG = @"MG";

/**
 
 Malawi.
 
*/
NSString *const Shopping_CountryCodeType_MW = @"MW";

/**
 
 Malaysia.
 
*/
NSString *const Shopping_CountryCodeType_MY = @"MY";

/**
 
 Maldives.
 
*/
NSString *const Shopping_CountryCodeType_MV = @"MV";

/**
 
 Mali.
 
*/
NSString *const Shopping_CountryCodeType_ML = @"ML";

/**
 
 Malta.
 
*/
NSString *const Shopping_CountryCodeType_MT = @"MT";

/**
 
 Marshall Islands.
 
*/
NSString *const Shopping_CountryCodeType_MH = @"MH";

/**
 
 Martinique.
 
*/
NSString *const Shopping_CountryCodeType_MQ = @"MQ";

/**
 
 Mauritania.
 
*/
NSString *const Shopping_CountryCodeType_MR = @"MR";

/**
 
 Mauritius.
 
*/
NSString *const Shopping_CountryCodeType_MU = @"MU";

/**
 
 Mayotte.
 
*/
NSString *const Shopping_CountryCodeType_YT = @"YT";

/**
 
 Mexico.
 
*/
NSString *const Shopping_CountryCodeType_MX = @"MX";

/**
 
 Federated States of Micronesia.
 
*/
NSString *const Shopping_CountryCodeType_FM = @"FM";

/**
 
 Republic of Moldova.
 
*/
NSString *const Shopping_CountryCodeType_MD = @"MD";

/**
 
 Monaco.
 
*/
NSString *const Shopping_CountryCodeType_MC = @"MC";

/**
 
 Mongolia.
 
*/
NSString *const Shopping_CountryCodeType_MN = @"MN";

/**
 
 Montserrat.
 
*/
NSString *const Shopping_CountryCodeType_MS = @"MS";

/**
 
 Morocco.
 
*/
NSString *const Shopping_CountryCodeType_MA = @"MA";

/**
 
 Mozambique.
 
*/
NSString *const Shopping_CountryCodeType_MZ = @"MZ";

/**
 
 Myanmar.
 
*/
NSString *const Shopping_CountryCodeType_MM = @"MM";

/**
 
 Namibia.
 
*/
NSString *const Shopping_CountryCodeType_NA = @"NA";

/**
 
 Nauru.
 
*/
NSString *const Shopping_CountryCodeType_NR = @"NR";

/**
 
 Nepal.
 
*/
NSString *const Shopping_CountryCodeType_NP = @"NP";

/**
 
 Netherlands.
 
*/
NSString *const Shopping_CountryCodeType_NL = @"NL";

/**
 
 Netherlands Antilles.
 
*/
NSString *const Shopping_CountryCodeType_AN = @"AN";

/**
 
 New Caledonia.
 
*/
NSString *const Shopping_CountryCodeType_NC = @"NC";

/**
 
 New Zealand.
 
*/
NSString *const Shopping_CountryCodeType_NZ = @"NZ";

/**
 
 Nicaragua.
 
*/
NSString *const Shopping_CountryCodeType_NI = @"NI";

/**
 
 Niger.
 
*/
NSString *const Shopping_CountryCodeType_NE = @"NE";

/**
 
 Nigeria.
 
*/
NSString *const Shopping_CountryCodeType_NG = @"NG";

/**
 
 Niue.
 
*/
NSString *const Shopping_CountryCodeType_NU = @"NU";

/**
 
 Norfolk Island.
 
*/
NSString *const Shopping_CountryCodeType_NF = @"NF";

/**
 
 Northern Mariana Islands.
 
*/
NSString *const Shopping_CountryCodeType_MP = @"MP";

/**
 
 Norway.
 
*/
NSString *const Shopping_CountryCodeType_NO = @"NO";

/**
 
 Oman.
 
*/
NSString *const Shopping_CountryCodeType_OM = @"OM";

/**
 
 Pakistan.
 
*/
NSString *const Shopping_CountryCodeType_PK = @"PK";

/**
 
 Palau.
 
*/
NSString *const Shopping_CountryCodeType_PW = @"PW";

/**
 
 Palestinian territory, Occupied.
 
*/
NSString *const Shopping_CountryCodeType_PS = @"PS";

/**
 
 Panama.
 
*/
NSString *const Shopping_CountryCodeType_PA = @"PA";

/**
 
 Papua New Guinea.
 
*/
NSString *const Shopping_CountryCodeType_PG = @"PG";

/**
 
 Paraguay.
 
*/
NSString *const Shopping_CountryCodeType_PY = @"PY";

/**
 
 Peru.
 
*/
NSString *const Shopping_CountryCodeType_PE = @"PE";

/**
 
 Philippines.
 
*/
NSString *const Shopping_CountryCodeType_PH = @"PH";

/**
 
 Pitcairn.
 
*/
NSString *const Shopping_CountryCodeType_PN = @"PN";

/**
 
 Poland.
 
*/
NSString *const Shopping_CountryCodeType_PL = @"PL";

/**
 
 Portugal.
 
*/
NSString *const Shopping_CountryCodeType_PT = @"PT";

/**
 
 Puerto Rico.
 
*/
NSString *const Shopping_CountryCodeType_PR = @"PR";

/**
 
 Qatar.
 
*/
NSString *const Shopping_CountryCodeType_QA = @"QA";

/**
 
 Reunion.
 
*/
NSString *const Shopping_CountryCodeType_RE = @"RE";

/**
 
 Romania.
 
*/
NSString *const Shopping_CountryCodeType_RO = @"RO";

/**
 
 Russian Federation.
 
*/
NSString *const Shopping_CountryCodeType_RU = @"RU";

/**
 
 Rwanda.
 
*/
NSString *const Shopping_CountryCodeType_RW = @"RW";

/**
 
 Saint Helena.
 
*/
NSString *const Shopping_CountryCodeType_SH = @"SH";

/**
 
 Saint Kitts and Nevis.
 
*/
NSString *const Shopping_CountryCodeType_KN = @"KN";

/**
 
 Saint Lucia.
 
*/
NSString *const Shopping_CountryCodeType_LC = @"LC";

/**
 
 Saint Pierre and Miquelon.
 
*/
NSString *const Shopping_CountryCodeType_PM = @"PM";

/**
 
 Saint Vincent and the Grenadines.
 
*/
NSString *const Shopping_CountryCodeType_VC = @"VC";

/**
 
 Samoa.
 
*/
NSString *const Shopping_CountryCodeType_WS = @"WS";

/**
 
 San Marino.
 
*/
NSString *const Shopping_CountryCodeType_SM = @"SM";

/**
 
 Sao Tome and Principe.
 
*/
NSString *const Shopping_CountryCodeType_ST = @"ST";

/**
 
 Saudi Arabia.
 
*/
NSString *const Shopping_CountryCodeType_SA = @"SA";

/**
 
 Senegal.
 
*/
NSString *const Shopping_CountryCodeType_SN = @"SN";

/**
 
 Seychelles.
 
*/
NSString *const Shopping_CountryCodeType_SC = @"SC";

/**
 
 Sierra Leone.
 
*/
NSString *const Shopping_CountryCodeType_SL = @"SL";

/**
 
 Singapore.
 
*/
NSString *const Shopping_CountryCodeType_SG = @"SG";

/**
 
 Slovakia.
 
*/
NSString *const Shopping_CountryCodeType_SK = @"SK";

/**
 
 Slovenia.
 
*/
NSString *const Shopping_CountryCodeType_SI = @"SI";

/**
 
 Solomon Islands.
 
*/
NSString *const Shopping_CountryCodeType_SB = @"SB";

/**
 
 Somalia.
 
*/
NSString *const Shopping_CountryCodeType_SO = @"SO";

/**
 
 South Africa.
 
*/
NSString *const Shopping_CountryCodeType_ZA = @"ZA";

/**
 
 South Georgia and the South Sandwich Islands.
 
*/
NSString *const Shopping_CountryCodeType_GS = @"GS";

/**
 
 Spain.
 
*/
NSString *const Shopping_CountryCodeType_ES = @"ES";

/**
 
 Sri Lanka.
 
*/
NSString *const Shopping_CountryCodeType_LK = @"LK";

/**
 
 Sudan.
 
*/
NSString *const Shopping_CountryCodeType_SD = @"SD";

/**
 
 Suriname.
 
*/
NSString *const Shopping_CountryCodeType_SR = @"SR";

/**
 
 Svalbard and Jan Mayen.
 
*/
NSString *const Shopping_CountryCodeType_SJ = @"SJ";

/**
 
 Swaziland.
 
*/
NSString *const Shopping_CountryCodeType_SZ = @"SZ";

/**
 
 Sweden.
 
*/
NSString *const Shopping_CountryCodeType_SE = @"SE";

/**
 
 Switzerland.
 
*/
NSString *const Shopping_CountryCodeType_CH = @"CH";

/**
 
 Syrian Arab Republic.
 
*/
NSString *const Shopping_CountryCodeType_SY = @"SY";

/**
 
 Taiwan, Province of China.
 
*/
NSString *const Shopping_CountryCodeType_TW = @"TW";

/**
 
 Tajikistan.
 
*/
NSString *const Shopping_CountryCodeType_TJ = @"TJ";

/**
 
 Tanzania, United Republic of.
 
*/
NSString *const Shopping_CountryCodeType_TZ = @"TZ";

/**
 
 Thailand.
 
*/
NSString *const Shopping_CountryCodeType_TH = @"TH";

/**
 
 Togo.
 
*/
NSString *const Shopping_CountryCodeType_TG = @"TG";

/**
 
 Tokelau.
 
*/
NSString *const Shopping_CountryCodeType_TK = @"TK";

/**
 
 Tonga.
 
*/
NSString *const Shopping_CountryCodeType_TO = @"TO";

/**
 
 Trinidad and Tobago.
 
*/
NSString *const Shopping_CountryCodeType_TT = @"TT";

/**
 
 Tunisia.
 
*/
NSString *const Shopping_CountryCodeType_TN = @"TN";

/**
 
 Turkey.
 
*/
NSString *const Shopping_CountryCodeType_TR = @"TR";

/**
 
 Turkmenistan.
 
*/
NSString *const Shopping_CountryCodeType_TM = @"TM";

/**
 
 Turks and Caicos Islands.
 
*/
NSString *const Shopping_CountryCodeType_TC = @"TC";

/**
 
 Tuvalu.
 
*/
NSString *const Shopping_CountryCodeType_TV = @"TV";

/**
 
 Uganda.
 
*/
NSString *const Shopping_CountryCodeType_UG = @"UG";

/**
 
 Ukraine.
 
*/
NSString *const Shopping_CountryCodeType_UA = @"UA";

/**
 
 United Arab Emirates.
 
*/
NSString *const Shopping_CountryCodeType_AE = @"AE";

/**
 
 United Kingdom.
 
*/
NSString *const Shopping_CountryCodeType_GB = @"GB";

/**
 
 United States.
 
*/
NSString *const Shopping_CountryCodeType_US = @"US";

/**
 
 NOTE: United States Minor Outlying Islands was
 defined in the eBay list previously
 but is no longer a viable option. This country
 will remain on eBay country list for backward
 compatibility. Use 'US' instead.
 
*/
NSString *const Shopping_CountryCodeType_UM = @"UM";

/**
 
 Uruguay.
 
*/
NSString *const Shopping_CountryCodeType_UY = @"UY";

/**
 
 Uzbekistan.
 
*/
NSString *const Shopping_CountryCodeType_UZ = @"UZ";

/**
 
 Vanuatu.
 
*/
NSString *const Shopping_CountryCodeType_VU = @"VU";

/**
 
 Venezuela.
 
*/
NSString *const Shopping_CountryCodeType_VE = @"VE";

/**
 
 Vietnam.
 
*/
NSString *const Shopping_CountryCodeType_VN = @"VN";

/**
 
 Virgin Islands, British.
 
*/
NSString *const Shopping_CountryCodeType_VG = @"VG";

/**
 
 Virgin Islands, U.S.
 
*/
NSString *const Shopping_CountryCodeType_VI = @"VI";

/**
 
 Wallis and Futuna.
 
*/
NSString *const Shopping_CountryCodeType_WF = @"WF";

/**
 
 Western Sahara.
 
*/
NSString *const Shopping_CountryCodeType_EH = @"EH";

/**
 
 Yemen.
 
*/
NSString *const Shopping_CountryCodeType_YE = @"YE";

/**
 
 No longer in use. See RS for Serbia and ME for Montenegro.
 
*/
NSString *const Shopping_CountryCodeType_YU = @"YU";

/**
 
 Zambia.
 
*/
NSString *const Shopping_CountryCodeType_ZM = @"ZM";

/**
 
 Zimbabwe.
 
*/
NSString *const Shopping_CountryCodeType_ZW = @"ZW";

/**
 
 NOTE: APO/FPO was defined in eBay list previously
 but they are not defined in ISO 3166. This country
 will remain on eBay country code list for backward
 compatibility.
  
*/
NSString *const Shopping_CountryCodeType_AA = @"AA";

/**
 
 NOTE: Guernsey was defined in eBay list previously
 but they are not defined in ISO 3166. This country
 will remain on eBay country list for backward
 compatibility.
  
*/
NSString *const Shopping_CountryCodeType_QM = @"QM";

/**
 
  NOTE: Jan Mayen was defined in eBay list previously
  but they are not defined in ISO 3166. This country
  will remain on eBay country list for backward
  compatibility.
  
*/
NSString *const Shopping_CountryCodeType_QN = @"QN";

/**
 
  NOTE: Jersey was defined in eBay list previously
  but they are not defined in ISO 3166. This country
  will remain on eBay country list for backward
  compatibility.
  
*/
NSString *const Shopping_CountryCodeType_QO = @"QO";

NSString *const Shopping_CountryCodeType_QP = @"QP";

/**
 
 Placeholder value. See
 <a href="http://developer.ebay.com/DevZone/shopping/docs/CallRef/types/simpleTypes.html#token">token</a>.
 
*/
NSString *const Shopping_CountryCodeType_CUSTOM_CODE = @"CustomCode";
