// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Shopping_SimpleUserType;
@class Shopping_CharityType;
@class Shopping_ProductIDType;
@class Shopping_UnitInfoType;
@class Shopping_ShippingCostSummaryType;
@class Shopping_DiscountPriceInfoType;
@class Shopping_QuantityInfo;
@class Shopping_NameValueListArrayType;
@class Shopping_DistanceType;
@class Shopping_AmountType;
@class Shopping_ItemCompatibilityListType;
@class Shopping_ReturnPolicyType;
@class Shopping_StorefrontType;
@class Shopping_BusinessSellerDetailsType;
@class Shopping_VariationsType;

/**
 
 Contains information for an item.
 
 
 @ingroup ShoppingInterface
*/
@interface Shopping_SimpleItemType : NSObject <PicoBindable> {

@private
    NSNumber *_bestOfferEnabled;
    Shopping_AmountType *_buyItNowPrice;
    NSString *_description;
    NSString *_itemID;
    NSNumber *_buyItNowAvailable;
    Shopping_AmountType *_convertedBuyItNowPrice;
    NSDate *_endTime;
    NSDate *_startTime;
    NSString *_viewItemURLForNaturalSearch;
    NSString *_listingType;
    NSString *_location;
    NSMutableArray *_paymentMethods;
    NSString *_galleryURL;
    NSMutableArray *_pictureURL;
    NSString *_postalCode;
    NSString *_primaryCategoryID;
    NSString *_primaryCategoryName;
    NSNumber *_quantity;
    Shopping_SimpleUserType *_seller;
    NSNumber *_bidCount;
    Shopping_AmountType *_convertedCurrentPrice;
    Shopping_AmountType *_currentPrice;
    Shopping_SimpleUserType *_highBidder;
    NSString *_listingStatus;
    NSNumber *_quantitySold;
    NSNumber *_reserveMet;
    NSMutableArray *_shipToLocations;
    NSString *_site;
    NSString *_timeLeft;
    NSString *_title;
    Shopping_ShippingCostSummaryType *_shippingCostSummary;
    Shopping_NameValueListArrayType *_itemSpecifics;
    NSNumber *_hitCount;
    NSString *_subtitle;
    NSString *_primaryCategoryIDPath;
    NSString *_secondaryCategoryID;
    NSString *_secondaryCategoryName;
    NSString *_secondaryCategoryIDPath;
    Shopping_CharityType *_charity;
    NSNumber *_germanMotorsSearchable;
    NSNumber *_getItFast;
    NSNumber *_gift;
    NSNumber *_pictureExists;
    NSNumber *_recentListing;
    Shopping_StorefrontType *_storefront;
    Shopping_DistanceType *_distanceFromBuyer;
    NSString *_country;
    NSNumber *_watchCount;
    NSString *_halfItemCondition;
    NSString *_sellerComments;
    Shopping_ReturnPolicyType *_returnPolicy;
    Shopping_AmountType *_minimumToBid;
    Shopping_ProductIDType *_productID;
    NSNumber *_autoPay;
    Shopping_BusinessSellerDetailsType *_businessSellerDetails;
    NSMutableArray *_paymentAllowedSite;
    NSNumber *_integratedMerchantCreditCardEnabled;
    Shopping_VariationsType *_variations;
    NSNumber *_handlingTime;
    NSNumber *_lotSize;
    NSNumber *_conditionID;
    NSString *_conditionDisplayName;
    NSString *_quantityAvailableHint;
    NSNumber *_quantityThreshold;
    Shopping_DiscountPriceInfoType *_discountPriceInfo;
    NSMutableArray *_excludeShipToLocation;
    NSNumber *_topRatedListing;
    NSString *_vhrUrl;
    NSNumber *_vhrAvailable;
    Shopping_QuantityInfo *_quantityInfo;
    Shopping_UnitInfoType *_unitInfo;
    NSNumber *_globalShipping;
    NSMutableArray *_any;
    NSString *_conditionDescription;
    NSNumber *_itemCompatibilityCount;
    Shopping_ItemCompatibilityListType *_itemCompatibilityList;
    NSNumber *_quantitySoldByPickupInStore;
    NSString *_sku;
    NSNumber *_newBestOffer;
    NSNumber *_eBayNowEligible;
    NSNumber *_eBayNowAvailable;
    NSNumber *_ignoreQuantity;
    NSNumber *_availableForPickupDropOff;
    NSNumber *_eligibleForPickupDropOff;

}


/**
 
 Whether the seller will accept a best offer for this item.
 This feature enables a buyer to make a lower-priced binding offer on a
 fixed price item. Buyers can't see how many offers have been made
 (only the seller can see this information). To make a best offer on a
 listing, use the eBay Web site.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *bestOfferEnabled;

/**
 
 The Buy It Now price of the item, returned in the currency of the site
 on which the item was listed.
 <br />
 <br />
 For auction listings, Buy It Now lets a user purchase the item at a fixed price and
 end the auction immediately. On most sites, after an auction has bids, the
 listing is no longer eligible for Buy It Now. However, calls can return
 BuyItNowPrice if the seller originally listed the item with a Buy It Now option. Use
 the Item.BidCount field to determine whether an auction with Buy It Now has bids or
 not, and use Item.BuyItNowAvailable to see if the Buy It Now option is still
 available.
 <br />
 <br />
 Price fields are returned as doubles, not necessarily in the traditional
 monetary format of the site's country. For example, a US Dollar value might be
 returned as 3.880001 instead of 3.88.
 <br>
 <br />
 For fixed-price (FixedPriceItem) listings, see CurrentPrice or ConvertedCurrentPrice instead.
 <br />
 <br />
 Returned only if an item was listed with a Buy It Now option.
 
 
 type : class Shopping_AmountType
*/
@property (nonatomic, retain) Shopping_AmountType *buyItNowPrice;

/**
 
 The seller's description of the item, if any. This can include
 HTML markup and JavaScript. See <a
 href="http://developer.ebay.com/DevZone/shopping/docs/CallRef/types/simpleTypes.html#string">string</a>
 in Simple Schema Types.
 <br>
 <br>
 Some sellers don't specify their own listing description.
 Instead, they use a stock description from a catalog available
 through eBay. (GetSingleItem doesn't return this stock information.)
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *description;

/**
 
 The ID that uniquely identifies the item listing. eBay generates this ID
 when an item is listed. This ID is unique across all eBay sites.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *itemID;

/**
 
 Indicates whether the item has an active Buy It Now option. On most sites, the
 Buy It Now option is disabled once a valid bid for the item has been accepted.
 To see if the item was listed with a Buy It Now option, see if the response
 includes Item.BuyItNowPrice.
 <br />
 <br />
 This field is returned only if the value is true.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *buyItNowAvailable;

/**
 
 The listing's Buy It Now Price (if any), converted into the currency
 of the site to which you sent this request.
 <br />
 <br />
 Price fields are returned as doubles, not necessarily in the traditional
 monetary format of the site's country. For example, a US Dollar value might be
 returned as 3.880001 instead of 3.88.
 <br />
 <br />
 Some eBay sites also support multi-item Buy It Now auctions, where you can buy
 multiple items from the same listing at a fixed price. See Item.BuyItNowAvailable.
 <br>
 <br>
 For fixed-price (FixedPriceItem) listings, see
 CurrentPrice or ConvertedCurrentPrice instead.
 <br>
 <br>
 Returned only if an item was listed with a Buy It Now option.
 <br>
 <br>
 For active items, refresh this value every 24 hours to pick up the current
 conversion rates (if this value has been converted).
 
 
 type : class Shopping_AmountType
*/
@property (nonatomic, retain) Shopping_AmountType *convertedBuyItNowPrice;

/**
 
 Time stamp (in <a href="http://developer.ebay.com/DevZone/shopping/docs/CallRef/types/simpleTypes.html#dateTime">GMT</a>)
 of when the listing is scheduled to end, or time stamp of the actual end time
 (if the item ended).
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *endTime;

/**
 
 Time stamp (in <a href="http://developer.ebay.com/DevZone/shopping/docs/CallRef/types/simpleTypes.html#dateTime">GMT</a>) that
 eBay recorded as the moment that the listing was made available.
 The start time returned by a search call may vary
 from the value returned by GetSingleItem.
 
 
 type : NSDate, wrapper for primitive date
*/
@property (nonatomic, retain) NSDate *startTime;

/**
 
 The URL to view this listing on eBay. This URL is optimized to support natural
 search. That is, this URL is designed to make items on eBay easier to find via
 popular Internet search engines. For example, this URL specifies the item title, and
 it is optimized for natural search: "_W0QQ" is like "?" (question mark), "QQ" is like
 "&" (ampersand), and "Z" is like "=" (equals sign). You shouldn't modify the
 query syntax in your application. For example, eBay won't recognize the URL if you
 change QQ to ?.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *viewItemURLForNaturalSearch;

/**
 
 The format of the listing, such as online auction, fixed price,
 or advertisement format.
 
 
 type: string constant in Shopping_ListingTypeCodeType.h
*/
@property (nonatomic, retain) NSString *listingType;

/**
 
 Physical location of the item, as specified by the seller.
 (This gives a general indication of where the item will be
 shipped or delivered from.)
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *location;

/**
 
 Identifies the payment method (such as PayPal) the seller
 will accept when the buyer pays for the item. <br>
 <br>
 <span class="tablenote"><b>Note:</b>
 If the seller only accepts PayPal, the buyer can still pay
 with a credit card. PayPal supports major credit cards.
 </span>
 <br>
 Payment methods are not applicable to eBay Real Estate advertisement
 listings, or other Classified Ad format listings.
 
 
 entry type : string constant in Shopping_BuyerPaymentMethodCodeType.h
*/

@property (nonatomic, retain) NSMutableArray *paymentMethods;

/**
 
 URL for a picture used as the Gallery thumbnail, if any. The image uses
 one of the following graphics formats: JPEG, BMP, TIF, or GIF. Only
 returned if the seller chose to show a gallery image.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *galleryURL;

/**
 
 Contains the URL for an image associated with the item, if any.
 Returned only if the seller included at least one picture
 in their listing. Note that this element does not return the URLs of
 pictures that the seller included in the Description via HTML IMG tags.
 <br>
 <br>
 Items listed the main eBay site can have a maximum of 12 picture URLs
 hosted by eBay Picture Services or a maximum of 12 picture URLs hosted externally (outside of eBay). Note that a listing can have up to
 24 picture URLs on the US eBay Motors site (for all vehicle listings),
 and on the eBay Canada Motors site.
 <br>
 <br>
 eBay uses the seller's first picture at the top of the listing's
 View Item page.
 
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, retain) NSMutableArray *pictureURL;

/**
 
 Postal code indicating the physical location of the item,
 as specified by the seller. (This gives a general indication of where
 the item will be shipped or delivered from.)
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *postalCode;

/**
 
 Numeric ID of the first (or only) category in which the item is listed.
 (Listings can appear in more than one category.)
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *primaryCategoryID;

/**
 
 Display name of the first (or only) category in which the item is
 listed. This is a fully qualified category breadcrumb
 (e.g., Computers & Networking:Laptops, Notebooks).
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *primaryCategoryName;

/**
 
 The number of items the seller is offering in the listing. (Subtract
 Item.QuantitySold from this value to calculate the number of items
 currently available for sale.)
 <br>
 <br>
 An auction listing always has a Quantity of 1. Basic fixed-price listings can
 have a Quantity of 1 or more.
 <br />
 <br />
 The listing's current or Buy It Now price is the price of the item in the
 listing.
 <br />
 <br />
 <span class="tablenote"><strong>Note:</strong>
 A seller can also offer multiple items for sale with a single
 price for all the items. For example, instead of listing 10 light bulbs
 for US 2.00 each, they might list 10 light bulbs for USD 20.00 (where
 you have to buy all 10). This is called a "lot."
 <br />
 <br />
 If the listing includes a lot, Quantity does not specify the lot size; it
 reflects how many lots are being sold. For example, if the original listing
 included 5 lots of 10 light bulbs each, Quantity would be 5.
 </span>
 <br />
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *quantity;

/**
 
 Container for information about this listing's seller.
 
 
 type : class Shopping_SimpleUserType
*/
@property (nonatomic, retain) Shopping_SimpleUserType *seller;

/**
 
 The number of bids that have been placed on the item.
 <br>
 <br>
 On most sites, the Buy It Now Option becomes unavailable once an auction
 has a valid bid. Note that the bid must be above any reserve price.
 <br>
 <br>
 <b>FindPopularItems: </b>For fixed-price listings, the BidCount
 value is the total number of items purchased so far (in the listing's
 lifetime).
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *bidCount;

/**
 
 The listing's Buy It Now Price (if any), converted into the currency
 of the site to which you sent this request.
 <br />
 <br />
 Price fields are returned as doubles, not necessarily in the traditional
 monetary format of the site's country. For example, a US Dollar value might be
 returned as 3.880001 instead of 3.88.
 <br>
 <br />
 Some eBay sites also support multi-item Buy It Now auctions, where you can buy
 multiple items from the same listing at a fixed price. See Item.BuyItNowAvailable.
 <br>
 <br>
 For fixed-price (FixedPriceItem) listings, see
 CurrentPrice or ConvertedCurrentPrice instead.
 <br>
 <br>
 Returned only if an item was listed with a Buy It Now option.
 <br>
 <br>
 For active items, refresh this value every 24 hours to pick up the current
 conversion rates (if this value has been converted).
 
 
 type : class Shopping_AmountType
*/
@property (nonatomic, retain) Shopping_AmountType *convertedCurrentPrice;

/**
 
 The current price of the item in the original listing currency.
 <br><br>
 For auction listings, this price is the starting minimum price (if the listing has no bids) or the current highest bid (if bids have been placed) for the item. This does not reflect the BuyItNow price.
 <br><br>
 For fixed-price and ad format listings, this is the current listing price.
 
 
 type : class Shopping_AmountType
*/
@property (nonatomic, retain) Shopping_AmountType *currentPrice;

/**
 
 The high bidder for competitive-bidding auctions that have ended and have a winning
 bidder. This indicates the user who purchased the item.
 <br>
 <br>
 Not returned for auctions that have received no bids, or for fixed price
 listings that are still active.
 
 
 type : class Shopping_SimpleUserType
*/
@property (nonatomic, retain) Shopping_SimpleUserType *highBidder;

/**
 
 Specifies a listing's status in eBay's processing workflow.
 If an item's EndTime is in the past, but no details about the
 buyer or high bidder are shown (and the user is not anonymous),
 use this listing status information to determine whether eBay has
 finished processing the listing.
 
 
 type: string constant in Shopping_ListingStatusCodeType.h
*/
@property (nonatomic, retain) NSString *listingStatus;

/**
 
 Number of items purchased so far from this listing. (Subtract this value from
 Item.Quantity to calculate the number of items currently available for sale.)
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *quantitySold;

/**
 
 Indicates whether any bids on this item are greater than the seller's
 reserve price for the listing (if any).
 <br>
 <br>
 A reserve is the lowest price at which the seller is willing to sell
 the item. The reserve price is higher than the listing's opening bid
 (minimum bid) and lower than the Buy It Now price, if any.
 (The reserve price is only known to the seller.)
 Some sellers don't set a reserve at all. If a listing does have
 a reserve price, the highest bidder will only win
 the item if their bid is also above that price.
 <br>
 <br>
 Only returned for online auctions that have a reserve price. (Fixed price, Store
 Inventory, and classified ad listings don't have reserve prices.)
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *reserveMet;

/**
 
 An international location or region to which the seller is willing
 to ship this item. Returned only for items that have ShipToLocations
 specified.
 <br>
 <br>
 <strong>Applicable values</strong>:
 <p class="ename">&bull;&nbsp;&nbsp; Americas</p>
 <p class="edef">(North, South, or Latin America)</p>
 <p class="ename">&bull;&nbsp;&nbsp; Asia</p>
 <p class="ename">&bull;&nbsp;&nbsp; Caribbean</p>
 <p class="ename">&bull;&nbsp;&nbsp; Europe</p>
 <p class="ename">&bull;&nbsp;&nbsp; EuropeanUnion</p>
 <p class="ename">&bull;&nbsp;&nbsp; LatinAmerica</p>
 <p class="ename">&bull;&nbsp;&nbsp; MiddleEast</p>
 <p class="ename">&bull;&nbsp;&nbsp; NorthAmerica</p>
 <p class="ename">&bull;&nbsp;&nbsp; Oceania</p>
 <p class="edef">(Pacific region other than Asia)</p>
 <p class="ename">&bull;&nbsp;&nbsp; SouthAmerica</p>
 <p class="ename">&bull;&nbsp;&nbsp; WillNotShip</p>
 <p class="edef">(No shipping, buyer must pick up the item)</p>
 <p class="ename">&bull;&nbsp;&nbsp; Worldwide</p>
 <p class="edef">(Seller will ship worldwide)</p>
 <p class="ename">&bull;&nbsp;&nbsp; 2-letter country identifier</p>
 <p class="edef">(See CountryCodeType for values)</p>
 
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, retain) NSMutableArray *shipToLocations;

/**
 
 The name of the eBay site on which the item was originally listed.
 For example, if the item is listed on the eBay US site,
 the value would be US. If it's listed on the eBay Germany site,
 the value would be Germany.
 <br>
 <br>
 The listing's original site can affect the values of converted
 (localized) prices (when your request specifies a site
 that is different from the listing's site).
 
 
 type: string constant in Shopping_SiteCodeType.h
*/
@property (nonatomic, retain) NSString *site;

/**
 
 Time left before the listing ends.
 The duration is represented in the ISO 8601 duration format (PnYnMnDTnHnMnS).
 For ended listings, the time left is PT0S (zero seconds).
 
 
 type : NSString, wrapper for primitive duration
*/
@property (nonatomic, retain) NSString *timeLeft;

/**
 
 Name of the item as it appears in the listing or in search and
 browse results.
 <br>
 <br>
 <b>For US eBay Motors vehicles only:</b> In item-retrieval
 calls (like GetSingleItem and GetMultipleItems), this value shows the
 vehicle Make and Model (e.g., "Buick : Skylark").
 <br>
 <br>
 <span class="tablenote"><b>Note:</b>
 GetSingleItem does not return the same Item.Title
 value for US eBay Motors listings. Here's why:
 <br>
 <br>
 In general, GetSingleItem maps to eBay's View Item page. The eBay Motors
 Web site's View Item page shows two vehicle titles in the title bar: One
 title is a label based on the Year, Make, Model, and Submodel (e.g.,
 "1996 Buick Skylark Limited"). The model is included unless it's "Other"
 or unspecified. The submodel is included if the seller specified a
 submodel. The other title is a path based on the Make and Model (e.g.,
 "Buick : Skylark"). The Item.Title value in GetSingleItem maps to this
 path.
 </span>
 <br />
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *title;

/**
 
 <span class="tablenote">
 <strong>Important:</strong> This container and its children do not provide reliable shipping cost information when returned by the FindPopularItems, FindProducts, GetMultipleItems and GetSingleItem calls. If a listing has shipping costs, use the GetShippingCosts call to get more details about the services and costs that the seller is offering.
 </span>
 
 
 type : class Shopping_ShippingCostSummaryType
*/
@property (nonatomic, retain) Shopping_ShippingCostSummaryType *shippingCostSummary;

/**
 
 Category-specific fields that the seller added to describe
 the listing. The names of these fields are different for items
 in different categories, so they're returned in a generic
 Name/Value structure. The field names are usually very well known
 within the category.
 <br>
 <br>
 For example, a book's item specifics might include a field like
 Publication Year=2007 (where Publication Year is returned in Name, and
 2007 is returned in Value), and a field like Format=Hardcover. But a car's
 item specifics would be different from a book's, with fields like Make=
 Toyota and Model=Prius. And a ticket's item specifics would be different
 from those of books and cars, with fields like EventType=Concerts and
 Venue=The Fillmore.
 <br>
 <br>
 One of the most common uses for item specifics is the item condition.
 <br>
 <br>
 Only returned if the seller included Item Specifics in the listing.
 
 
 type : class Shopping_NameValueListArrayType
*/
@property (nonatomic, retain) Shopping_NameValueListArrayType *itemSpecifics;

/**
 
 The number of times the listing's View Item page has been viewed (as determined by
 eBay). Only returned if the seller has chosen to include a hit counter in the
 listing, and if the seller has also chosen to make the listing's hit count publicly
 visible. This field is retrieved asynchronously. If you believe the item has a
 publicly visible hit count, but this field is not returned, retry the call.
 <br>
 <br>
 Not applicable to Half.com
 
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, retain) NSNumber *hitCount;

/**
 
 Subtitle of the item. Only returned if the seller included a
 subtitle for the listing.
 <br>
 <br>
 For US eBay Motors passenger vehicle, motorcycle, and "other vehicle"
 categories or listings in CA eBay Motors passenger vehicle and
 motorcycle categories, the seller's subtitle is only available
 in the Item.ItemSpecifics node. Call GetSingleItem with
 IncludeSelector=ItemSpecifics to retrieve a listing's Item Specifics.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *subtitle;

/**
 
 The fully qualified ID breadcrumb (path) of the first category.
 For example, if the primary category ID is 45678, and its parent
 category's ID is 123, the breadcrumb (path) would be 123:45678.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *primaryCategoryIDPath;

/**
 
 ID of the second category in which the item is listed. Returned only if
 the seller listed a second category.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *secondaryCategoryID;

/**
 
 Name of the second category in which the item is listed. Returned only if
 the seller listed a second category.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *secondaryCategoryName;

/**
 
 The fully qualified ID breadcrumb (path) of the second category. For example, if the
 secondary category ID is 45678, and its parent category's ID is 123, the breadcrumb
 (path) would be 123:45678. Returned only if the seller listed a second category.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *secondaryCategoryIDPath;

/**
 
 Identifier for a Giving Works listing and the benefiting nonprofit charity
 organization.
 
 
 type : class Shopping_CharityType
*/
@property (nonatomic, retain) Shopping_CharityType *charity;

/**
 
 The item is featured in eBay search results on the mobile.de partner site.
 Applicable to eBay Germany.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *germanMotorsSearchable;

/**
 
 The Get It Fast feature and icon are no longer supported in eBay listings.
 
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *getItFast;

/**
 
 If true, a generic gift icon displays next the listing's title in search and
 browse pages.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *gift;

/**
 
 Returns true if the item has an associated picture. Not returned
 if value is false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *pictureExists;

/**
 
 Returns true if the item listing is no more than one day old. Not returned
 if value is false.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *recentListing;

/**
 
 Returns the seller's store information if the seller has an eBay store.
 Returns a blank store if the seller does not have an eBay storefront.
 
 
 type : class Shopping_StorefrontType
*/
@property (nonatomic, retain) Shopping_StorefrontType *storefront;

/**
 
 The distance of the item from the buyer. The DistanceFromBuyer unit (miles
 or kilometers) varies by site. If the country whose site you are
 searching, e.g. India, uses kilometers, then the DistanceFromBuyer unit is
 kilometers. Otherwise, e.g. if the country is US or UK, then the
 DistanceFromBuyer unit is miles. DistanceFromBuyer is returned if a
 value for PostalCode is supplied in the request.
 
 
 type : class Shopping_DistanceType
*/
@property (nonatomic, retain) Shopping_DistanceType *distanceFromBuyer;

/**
 
 A two-letter code that represents the country in which the item is located. 
 <br><br>
 To see the list of currently supported country
 codes, and the English names associated with each code (e.g., KY="Cayman Islands"),
 call the Trading API's <b>GeteBayDetails</b>, with <b>DetailName</b> set to <b>CountryDetails</b>,
 and then look for <b>CountryDetails.Country</b> fields in the response.
 <br><br>
 Most of the codes that eBay uses conform to the ISO 3166 standard, but some of the
 codes in the ISO 3166 standard are not used by eBay. Plus, there are some non-ISO
 codes in the eBay list. 
 <br/><br/>
 <span class="tablenote">
 <strong>Note:</strong> The 
 <pre>
 &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;a xmlns="urn:ebay:apis:eBLBaseComponents" xmlns:ns="urn:ebay:apis:eBLBaseComponents" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xs="http://www.w3.org/2001/XMLSchema" href="types/CountryCodeType.html"&gt;CountryCodeType&lt;/a&gt;
 </pre>
  list is only a subset of all supported country codes, so to ensure that you are seeing the latest list, you should make a <b>GeteBayDetails</b> call as explained above.
 </span>
 
 type: string constant in Shopping_CountryCodeType.h
*/
@property (nonatomic, retain) NSString *country;

/**
 
 Number of users who have placed the item on their Watch list.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *watchCount;

/**
 
 Returns the Half.com condition code for the item. For example, "brand new,"
 "used," etc.
 
 
 type: string constant in Shopping_HalfItemConditionCodeType.h
*/
@property (nonatomic, retain) NSString *halfItemCondition;

/**
 
 Notes that the Seller made when they listed the item. Not returned if the Seller
 did not make any comments.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *sellerComments;

/**
 
 If a seller specified return policy details, then this container has fields with
 those details. The fields that can be returned in this container vary by site.
 
 
 type : class Shopping_ReturnPolicyType
*/
@property (nonatomic, retain) Shopping_ReturnPolicyType *returnPolicy;

/**
 
 Smallest amount the next bid on the item can be. Returns same value as
 Item.StartPrice (if no bids have yet been placed) or CurrentPrice plus
 BidIncrement (if at least one bid has been placed). Only applicable to
 competitive-bid auction listings. Returns null for basic Fixed Price
 (FixedPriceItem) and Ad type listings.
 
 
 type : class Shopping_AmountType
*/
@property (nonatomic, retain) Shopping_AmountType *minimumToBid;

/**
 
 A prototype description of a well-known type of item, such as a popular book.
 <br>
 <br>
 When returned for GetSingleItem, is always of type Reference, and serves as a global
 reference ID for an eBay catalog product.
 <br>
 <br>
 When used as input, retrieves product details for one specific product. Specify the
 ID as a string, and use the type attribute to indicate the nature of the ID you are
 specifying.
 <br>
 <br>
 The request requires either QueryKeywords or
 ProductID, but these fields cannot be used together.
 
 
 type : class Shopping_ProductIDType
*/
@property (nonatomic, retain) Shopping_ProductIDType *productID;

/**
 
 If true, the seller requires immediate payment for the item. If false (or
 not specified), immediate payment is not requested. Buyers must have a
 PayPal account to purchase items that require immediate payment.
 <br><br>
 A seller can choose to require immediate payment for Fixed Price and Buy
 It Now listings. If a Buy It
 Now item ends as an auction (that is, if the Buy It Now option is removed
 due to bids being placed on the listing), the immediate payment
 requirement does not apply.
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 The value of the AutoPay flag indicates the seller's stated preference
 only. It does not indicate whether the listing is still a candidate for
 purchase via immediate payment. For example, if a listing receives bids
 and no longer qualifies for immediate payment, the value of the AutoPay
 flag does not change.
 </span>
 <br>
 Only applicable to items listed on PayPal-enabled sites and in categories
 that support immediate payment. Not applicable to Half.com.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *autoPay;

/**
 
 Returns the seller's business information. Set the SellerBusinessCodeType
 to 'Commercial' in the request to return the related information. This is only
 applicable for sites where Business Seller options are supported.
 
 
 type : class Shopping_BusinessSellerDetailsType
*/
@property (nonatomic, retain) Shopping_BusinessSellerDetailsType *businessSellerDetails;

/**
 
 Enables you to view the sites on which an item can be purchased,
 based on the payment methods offered for the item.
 
 
 entry type : string constant in Shopping_SiteCodeType.h
*/

@property (nonatomic, retain) NSMutableArray *paymentAllowedSite;

/**
 
 Indicates whether the item can be paid for through a payment gateway account. If
 IntegratedMerchantCreditCardEnabled is true, then integrated merchant credit card is
 enabled for credit cards because the seller has a payment gateway account. Therefore,
 if IntegratedMerchantCreditCardEnabled is true, and AmEx, Discover, or VisaMC is
 returned for an item, then on checkout, an online credit-card payment is processed
 through a payment gateway account.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *integratedMerchantCreditCardEnabled;

/**
 
 Variations are multiple similar (but not identical) items in a single fixed-price listing. For example, a single listing could contain multiple
 items of the same brand and model that vary by color and size (like "Blue, Large" and
 "Black, Medium"). Each variation can have its own quantity and price. Only returned
 if the listing contains multiple variations.
 
 
 type : class Shopping_VariationsType
*/
@property (nonatomic, retain) Shopping_VariationsType *variations;

/**
 
 Specifies the maximum number of business days the seller commits to for preparing an item to be shipped after receiving a cleared payment. When listing the item, the seller sets this to an integer value (<code>0</code>, <code>1</code>, <code>2</code>, <code>3</code>, <code>4</code>, <code>5</code>, <code>10</code>, <code>15</code> or <code>20</code>) corresponding to the number of days. This time does not include the shipping time (the carrier's transit time).
 <br/><br/>
 <strong>GetSingleItem</strong> or <strong>GetMultipleItems</strong> returns <strong>HandlingTime</strong> only when shipping service options are specified for the item and the seller specified a handling time.
 <br/><br/>
 A <strong>HandlingTime</strong> value of <code>0</code> indicates <em>same day handling</em> for an item. In this case, the seller's shipping commitment depends on the <em>order cut off time</em> set in the seller's user preferences. This defaults to 2:00 PM local time on most sites, but it can be overridden by the seller for the eBay site on which the item is listed. For orders placed (and cleared payment received) before the local order cut off time, the item must be shipped by the end of the current day. For orders completed on or after the order cut off time, the item must be shipped by the end of the following day (excluding weekends and local holidays).
 <br><br>
 <span class="tablenote">
 <strong>Note:</strong> If a same day shipping carrier is selected, and the carrier delivers on one or both weekend days, sellers on the eBay US site are assumed to be open for business on the same days, and those days will be used when calculating total shipping time.
 </span>
 Valid for flat and calculated shipping. Does not apply when there is no shipping, or when using local pickup only or freight shipping.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *handlingTime;

/**
 
 A lot is a set of two or more similar items that must be purchased together in
 a single transaction. A listing can have multiple lots (instead of multiple
 items). When LotSize is specified, the listing price reflects the price of
 each lot (not each item within the lot). In this case, Quantity indicates the
 number of lots being listed, and LotSize indicates the number of items in each
 lot. (If a listing has no lots, Quantity indicates the number of separate
 items being listed.) Important: Lot items can be listed only in lot-enabled
 categories. GetCategories returns lot size disabled with a value of true
 for categories that do not support lots.
 <br /><br />
 Not applicable to Half.com.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *lotSize;

/**
 
 The numeric ID (e.g., 1000) for the item condition.
 Only returned when the seller specified ConditionID in their listing. Also see ItemSpecifics in case the seller used that
 field for the condition instead.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *conditionID;

/**
 
 The human-readable label for the item condition.
 Display names are localized for the site on
 which they're listed (not necessarily the site on which
 they're viewed).<br>
 <br>
 Most categories use the same display name for the
 same condition ID. Some categories may override the display name
 based on buyer expectations for items in the category.
 For example, condition ID 1000 could be called
 "New" in one category and "New with tags" in another.<br>
 <br>
 Behind the scenes, eBay's search engine uses the ID
 (not the display name) to determine whether items are
 new, used, or refurbished.<br>
 <br>
 Only returned when ConditionID is returned. Also see ItemSpecifics
 in case the seller used that field for the condition instead.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *conditionDisplayName;

/**
 
 Indicates the type of message that will be returned describing the quantity
 available for the item.
 
 
 type: string constant in Shopping_QuantityAvailableHintCodeType.h
*/
@property (nonatomic, retain) NSString *quantityAvailableHint;

/**
 
 The quantity threshold above which the seller prefers not to show the actual
 quantity available. Returned when the quantity available is greater than the
 value of quantity threshold. Currently, 10 is the only available value for
 this threshold.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *quantityThreshold;

/**
 
 This container provides information for an item that has a Strikethrough Price
 (STP) or a Minimum Advertised Price (MAP) discount pricing treatment. STP and MAP apply only to fixed-price listings. STP is available on the US, eBay Motors, UK, Germany, Canada (English and French), France, Italy, and Spain sites, while MAP is available only on the US site.
 <br > <br >
 Discount pricing is available to qualified sellers (and their associated developers) who
 participate in the Discount Pricing Program. Once qualified, sellers receive a
 "special account flag" (SAF) that allows them to apply Discount Pricing to both MSKU
 and Non-MSKU items.
 
 
 type : class Shopping_DiscountPriceInfoType
*/
@property (nonatomic, retain) Shopping_DiscountPriceInfoType *discountPriceInfo;

/**
 
 Use this field to specify an international country or region, or a special domestic
 location (for sites supporting this feature, currently US, UK, DE) to where you
 will not ship the associated item. On input, repeat this element for each
 location that you want to exclude as a shipping destination for your item.
 <br><br>
 Set ShipToRegistrationCountry to true to have your ExcludeShipToLocation
 settings applied to your listing. The locations you have excluded display in
 the Shipping and Handling section of your item listing.
 <br><br>
 If a buyer's primary ship-to location is a location that you have listed as
 an excluded ship-to location (or if the buyer does not have a primary ship-to
 location), they will receive an error message if they attempt to buy or place
 a bid on your item.
 <br><br>
 The exclude ship-to location values are eBay regions and countries. To see
 the valid exclude ship-to locations for a specified site, call GeteBayDetails
 with DetailName set to ExcludeShippingLocationDetails. Repeat GeteBayDetails
 for each site on which you list.
 <br><br>
 This field works in conjunction with Item.ShipToLocations to create a set of
 international countries and regions to where you will, and will not, ship.
 You can list a region in the ShipToLocations field, then exclude specific
 countries within that region with this field (for example, you can specify
 Africa in ShipToLocations, yet exclude Chad with a ExcludeShipToLocation
 setting). In addition, if your ShipToLocations is Worldwide, you can use
 this field to specify both regions and countries that you want to exclude
 from your shipping destinations.
 <br><br>
 You can specify a default set of locations to where you will not ship in My
 eBay. If you create an Exclude Ship-To List, it is, by default, in effect
 when you list items. However, if you specify any value in this field on
 input, it nullifies the default settings in your Exclude Ship-To List. (If
 you use ExcludeShipToLocation when you list an item, you will need to list
 all the locations to where you will not ship the associated item, regardless
 of the default settings in your Exclude Ship-To List.)
 <br><br>
 Specify NONE in this field to override the default Exclude Ship-To List you
 might have set up in My eBay and indicate that you do not want to exclude any
 shipping locations from the respective item listing.
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 To enable your default Exclude Ship-To List, you must enable Exclude
 Shipping Locations and Buyer Requirements in your My eBay Site Preferences.
 For details, see the KnowledgeBase Article
 <a href="https://ebaydts.com/eBayKBDetails?KBid=1495">HowTo: ExcludeShipToLocation</a>.
 </span>
 
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, retain) NSMutableArray *excludeShipToLocation;

/**
 
 This field is only applicable to the US, UK, and Germany sites, and will only be returned if the seller qualifies as a Top-Rated Seller. The current requirements for US sellers to
 qualify as Top-Rated Sellers are summarized below. The requirements on the UK and Germany sites are different. To see those requirements, see the UK or Germany customer support/help pages.
 <ul>
 <li>100 or more selling transactions over the last 12-month period</li>
 <li>One thousand dollars or more in sales to US buyers over the last 12-month period</li>
 <li>Shipment tracking information provided to buyer within handling time
 for at least 90 percent of their listings</li>
 <li>Two percent or less of transactions with one or more defects over the current evaluation period</li>
 <li>Less than one percent of eBay Buyer Protection and/or PayPal Purchase Protection cases can end without seller resolution</li>
 </ul>
 <br/><br/>
 If this flag is returned for a listing, it indicates that the listing meets the new
 requirements for a Top-Rated Listing. The following must be offered by a US seller for the listing to become a Top-Rated Listing on the US site:
 <ul>
 <li>14-day (or longer) return policy with Money Back option</li>
 <li>Same-day or 1 business day handling time</li>
 </ul>
 <br/><br/>
 The <b>Top-Rated Plus</b> seal appears on the View Item
 page for all Top-Rated Listings. US Top-Rated Sellers get a
 20 percent discount on their FVF for all listings that qualify as Top-Rated Listings.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *topRatedListing;

/**
 
 The URL to the eBay Motors item's full Vehicle History Report.
 Only returned when the item has a Vehicle History Report.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *vhrUrl;

/**
 
 If true, the eBay Motors item has a Vehicle History Report
 associated with it.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *vhrAvailable;

/**
 
 This container consists of the <b>MinimumRemnantSet</b>
 field, which sets the minimum amount of event tickets that can
 remain in the fixed-price listing's inventory after a buyer
 purchases one or more tickets (but not all) from the listing.
 <br/><br/>
 This field is currently only applicable for event ticket listings in
 US and CA, but may apply to other categories in the future. It is
 only returned if set by the seller in the listing.
 
 
 type : class Shopping_QuantityInfo
*/
@property (nonatomic, retain) Shopping_QuantityInfo *quantityInfo;

/**
 
    Contains information about the weight, volume or other quantity measurement of a listed item so buyers can compare per-unit prices. The European Union requires listings for certain types of products to include the price per unit. eBay uses this information and the item's listed price to calculate and display the unit price on eBay EU sites. 
    <br/><br/>
                   <span class="tablenote">
                   <strong>Note:</strong> This information is currently required only for business sellers, and only for listings with a Buy It Now option.
                   </span>
    
 
 type : class Shopping_UnitInfoType
*/
@property (nonatomic, retain) Shopping_UnitInfoType *unitInfo;

/**
 
    Indicates whether eBay's Global Shipping Program is offered for the listing. If the value of <strong>GlobalShipping</strong> is <code>true</code>, the Global Shipping Program is the default international shipping option for the listing, and eBay designates an appropriate international shipping service. If the value of <strong>GlobalShipping</strong> is <code>false</code>, the seller is responsible for specifying an international shipping service for the listing if desired.
    
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *globalShipping;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, retain) NSMutableArray *any;

/**
 
 This string field is used by the seller to more clearly describe the condition of
 items that are not brand new. 
 <br><br>
 The <b>ConditionDescription</b> field is available for all
 categories, including categories where the condition type is not applicable
 (e.g., Antiques). This field is applicable for all item conditions except
 "New", "Brand New", "New with tags", and "New in box". If
 <b>ConditionDescription</b> is used with these conditions (Condition
 IDs 1000-1499), eBay will simply ignore this field if included, and eBay will
 return a warning message to the user.
 <br><br>
 This field should only be used to further clarify the condition of the used item.
 For example, "The right leg of the chair has a small scratch, and on the seat
 back there is a light blue stain about the shape and size of a coin." It should
 not be used for branding, promotions, shipping, returns, payment or other
 information unrelated to the condition of the item. Make sure that the condition
 type (<b>Item.ConditionID</b>), condition description, item description
 (<b>Item.Description</b>), and the listing's pictures do not contradict
 one another.
 <br><br>
 The <b>ConditionDescription</b> field is only returned if a condition
 description is specified in the listing.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *conditionDescription;

/**
 
 Indicates the number of compatible applications specified for the given item. Applies to items listed with fitment by application only (either manually or with a catalog product that supports compatibility).
 <br><br>
 Not returned if the item has no specified compatible applications.
 <br><br>
 To retrieve the list of compatibility count and compatibility information, pass <strong>IncludeSelector</strong> in the request with a value of <code>Compatibility</code>.
 <br><br>
 Parts Compatibility is supported in limited Parts & Accessories categories, on the eBay Motors (US) site (site ID 100) only.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *itemCompatibilityCount;

/**
 
 A list of parts compatibility information specified as name and value pairs, describing an assembly with which a part is compatible (i.e., compatibility by application). For example, to specify a part's compatibility with a vehicle, the name (search name) would map to standard vehicle characteristics (e.g., Year, Make, Model, Trim, and Engine). The values describe the specific vehicle, such as a 2006 Honda Accord. Use the Product Metadata API to retrieve valid search names and corresponding values.
 <br><br>
 Not returned if the item has no specified compatible applications.
 <br><br>
 To retrieve the list of compatibility count and compatibility information, pass <strong>IncludeSelector</strong> in the request with a value of <code>Compatibility</code>.
 <br><br>
 Parts Compatibility is supported in limited Parts & Accessories categories, on the eBay Motors (US) site (site ID 100) only.
 
 
 type : class Shopping_ItemCompatibilityListType
*/
@property (nonatomic, retain) Shopping_ItemCompatibilityListType *itemCompatibilityList;

/**
 
 This field indicates the total quantity of items sold and picked up by buyers using the In-Store Pickup option. This value is the total number of items purchased by one or more buyers using the In-Store Pickup option, and is not the total number of In-Store Pickup orders. So, if two buyers selected the In-Store Pickup option, but each of these buyers bought a quantity of five of these items (in same purchase), the <b>Item.SellingStatus.QuantitySoldByPickupInStore</b> value would be '10' and not '2'.
 <br>
 <br>
 In the case of multi-variation, fixed-price listings, each <b>Item.Variations.Variation.SellingStatus.QuantitySoldByPickupInStore</b> value indicates the total quantity of that corresponding item variation (for example, large blue shirts) sold and picked up by buyers using the In-Store Pickup option, and the <b>Item.SellingStatus.QuantitySoldByPickupInStore</b> value would be the total quantity of all item variations sold for the listing.
 <br>
 <br>
 This field will only be returned if the listing is eligible for In-Store Pickup.
 <br/><br/>
 <span class="tablenote">
 <strong>Note:</strong> At this time, the In-Store Pickup feature is generally only available to large retail merchants, and can only be applied to multi-quantity, fixed-price listings.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, retain) NSNumber *quantitySoldByPickupInStore;

/**
 
 A SKU (stock keeping unit) is an identifier defined by a seller.
 Some sellers use SKUs to track complex flows of products
 and information on the client side.
 A seller can specify a SKU when listing an item with AddItem
 and related calls. eBay preserves the SKU on the item, enabling you
 to obtain it before and after an order line item is created.
 (SKU is recommended as an alternative to ApplicationData.)<br>
 <br>
 A SKU is not required to be unique. A seller can specify a
 particular SKU on one item or on multiple items.
 Different sellers can use the same SKUs.<br>
 <br>
 If the SKU is unique across a seller's active listings, and if the seller
 listed the item by using AddFixedPriceItem or RelistFixedPriceItem, the
 seller can also set Item.InventoryTrackingMethod to SKU in those calls.
 This allows the seller to use SKU instead of ItemID as a unique identifier
 in subsequent calls, such as GetItem and ReviseInventoryStatus.
 If both ItemID and SKU are specified in calls that support the use of
 SKU as a unique identifier, the ItemID value takes precedence.<br>
 <br>
 For multi-variation listings, the SKU can be used to uniquely identify a variation that is being revised or relisted.
 If InventoryTrackingMethod is ItemID, an ItemID is also required.
 When both SKU and VariationSpecifics are passed in the request, the variation specifics take precedence as the unique identifier. <br>
 <br>
 <span class="tablenote"><b>Note:</b>
 The eBay Web site UI cannot identify listings by SKU. For example,
 My eBay pages and Search pages all identify listings by item ID.
 When a buyer contacts you via eBay's messaging functionality, eBay
 uses the item ID as the identifier. Buyer-focused APIs (like the
 Shopping API) also do not support SKU as an identifier.
 </span>
 <b>For revising and relisting only:</b>
 To remove a SKU when you revise or relist an item, use DeletedField.
 (You cannot remove a SKU when Item.InventoryTrackingMethod is set
 to SKU.)<br>
 <br>
 For GetMyeBaySelling, this is only returned if set.
 <br>
 Not applicable to Half.com.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, retain) NSString *sku;

/**
 
 This boolean field will be returned as 'true' if a fixed-price listing is requiring immediate payment, and the item's category supports Immediate Payment for Best Offers.  Initially, Immediate Payment for Best Offers will be supported by the Computers & Tablets, Jewelry & Watches, and Art categories, but this feature will get enabled in more categories going forward.
 <br/><br/>
 If the Immediate Payment for Best Offers feature is enabled for a fixed-price listing, and a buyer's Best Offer for the item is accepted by the seller, that buyer will be expected to pay immediately for the item, or that buyer will run the risk of losing the item to another buyer since that item will remain on sale until payment is made.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *ebayNewBestOffer;

/**
 
 This boolean field indicates that the listing is eligible for eBay Now delivery, but it doesn't necessarily mean that items are available for purchase through the eBay Now method of delivery. The <b>eBayNowAvailable</b> field actually indicates whether or not items are available for purchase through eBay Now.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayNowEligible;

/**
 
 This boolean field will be returned as 'true' if the item is available for eBay Now delivery. However, buyers should realize that they must be in an area where eBay Now delivery is available. eBay Now is currently available on the San Francisco Peninsula (from San Francisco to San Jose), in Chigago, in Dallas, and in the New York City boroughs of Manhattan, Brooklyn, and Queens.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eBayNowAvailable;

/**
 
 This field will only be returned (as 'True') in the case where items in a listing are only available to buyers through a local fulfillment method such as In-Store Pickup, eBay Now, or Click and Collect. And if a listing is truly a "local fulfillment" listing only, the value in the <b>Item.Quantity</b> field (for single-variation listings) or the <b>Variation.Quantity</b> field (for multi-variation listings) will default to '0' even though the quantity available is technically not zero, since items in the listing are still available through one or more local fulfillment methods.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *ignoreQuantity;

/**
 
 This boolean field will be returned as 'true' if the seller has made the item available for the "Click and Collect" program. With the 'Click and Collect' feature, a buyer can purchase certain items on eBay and collect them at a local store. Buyers are notified by eBay once their items are available. The "Click and Collect" feature is only available to large merchants on the UK and Australia sites. UK and Australian buyers should realize that they must be in an area where "Click and Collect" is available. This field is not returned if 'false'.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *availableForPickupDropOff;

/**
 
 This field will be returned as 'true' in <b>GetItem</b> if the item is eligible for the "Click and Collect" feature. With the 'Click and Collect' feature, a buyer can purchase certain items on eBay and collect them at a local store. Buyers are notified by eBay once their items are available. The "Click and Collect" feature is only available to large merchants on the UK and Australia sites. UK and Australian buyers should realize that they must be in an area where "Click and Collect" is available. This field is not returned if 'false'.
 
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, retain) NSNumber *eligibleForPickupDropOff;


@end
