// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_ReviewType.h"

@implementation Shopping_ReviewType

@synthesize url = _url;
@synthesize title = _title;
@synthesize rating = _rating;
@synthesize text = _text;
@synthesize userID = _userID;
@synthesize creationTime = _creationTime;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"URL" propertyName:@"url" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"url"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Title" propertyName:@"title" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"title"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Rating" propertyName:@"rating" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"rating"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Text" propertyName:@"text" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"text"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserID" propertyName:@"userID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"userID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CreationTime" propertyName:@"creationTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"creationTime"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}



-(void)dealloc {
    self.url = nil;
    self.title = nil;
    self.rating = nil;
    self.text = nil;
    self.userID = nil;
    self.creationTime = nil;
    self.any = nil;
}

@end
