// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Shopping_AbstractResponseType.h"


@class Shopping_ShippingDetailsType;
@class Shopping_PickUpInStoreDetailsType;
@class Shopping_ShippingCostSummaryType;

/**
 
 Response to call of GetShippingCosts.
 
 
 @ingroup ShoppingInterface
*/
@interface Shopping_GetShippingCostsResponseType : Shopping_AbstractResponseType {

@private
    Shopping_ShippingDetailsType *_shippingDetails;
    Shopping_ShippingCostSummaryType *_shippingCostSummary;
    Shopping_PickUpInStoreDetailsType *_pickUpInStoreDetails;

}


/**
 
 Shipping-related details for the specified item. This container is only
 returned if IncludeDetails is true on input. Any error about shipping services
 (returned by a vendor of eBay's who calculates shipping costs) is returned in
 ShippingRateErrorMessage. Errors from a shipping service are likely to be related to
 issues with shipping specifications, such as package size and the selected shipping
 method not supported by a particular shipping service.
 
 
 type : class Shopping_ShippingDetailsType
*/
@property (nonatomic, retain) Shopping_ShippingDetailsType *shippingDetails;

/**
 
 Shipping-related details for the specified item. Any error about shipping services
 (returned by a vendor of eBay's who calculates shipping costs) is returned in
 ShippingRateErrorMessage. Errors from a shipping service are likely to be related to
 issues with shipping specifications, such as package size and the selected shipping
 method not supported by a particular shipping service.
 
 
 type : class Shopping_ShippingCostSummaryType
*/
@property (nonatomic, retain) Shopping_ShippingCostSummaryType *shippingCostSummary;

/**
 
 This container is returned in <b>GetShippingCosts</b> if In-Store Pickup is set for the listing.
 <br/><br/>
 <span class="tablenote">
 <strong>Note:</strong> At this time, the In-Store Pickup feature is generally only available to large retail merchants, and can only be applied to multi-quantity, fixed-price listings. 
 </span>
 This container is only returned if the version of the API is greater than or equal to 869.
 
 
 type : class Shopping_PickUpInStoreDetailsType
*/
@property (nonatomic, retain) Shopping_PickUpInStoreDetailsType *pickUpInStoreDetails;


@end
