// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Finding_DiscountPriceInfo.h"
#import "Finding_Amount.h"

@implementation Finding_DiscountPriceInfo

@synthesize originalRetailPrice = _originalRetailPrice;
@synthesize minimumAdvertisedPriceExposure = _minimumAdvertisedPriceExposure;
@synthesize pricingTreatment = _pricingTreatment;
@synthesize soldOnEbay = _soldOnEbay;
@synthesize soldOffEbay = _soldOffEbay;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"originalRetailPrice" propertyName:@"originalRetailPrice" type:PICO_TYPE_OBJECT clazz:[Finding_Amount class]];
    [map setObject:ps forKey:@"originalRetailPrice"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"minimumAdvertisedPriceExposure" propertyName:@"minimumAdvertisedPriceExposure" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"minimumAdvertisedPriceExposure"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"pricingTreatment" propertyName:@"pricingTreatment" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"pricingTreatment"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"soldOnEbay" propertyName:@"soldOnEbay" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"soldOnEbay"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"soldOffEbay" propertyName:@"soldOffEbay" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"soldOffEbay"];
    
    return map;
}



-(void)dealloc {
    self.originalRetailPrice = nil;
    self.minimumAdvertisedPriceExposure = nil;
    self.pricingTreatment = nil;
    self.soldOnEbay = nil;
    self.soldOffEbay = nil;
}

@end
