// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "ConversionRateResponse.h"

@implementation ConversionRateResponse

@synthesize conversionRateResult = _conversionRateResult;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"ConversionRateResponse" nsUri:@"http://www.webserviceX.NET/"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ConversionRateResult" propertyName:@"conversionRateResult" type:PICO_TYPE_DOUBLE clazz:nil];
    [map setObject:ps forKey:@"conversionRateResult"];
    
    return map;
}




@end
