// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_ItemCompatibilityType.h"
#import "Shopping_NameValueListType.h"

@implementation Shopping_ItemCompatibilityType

@synthesize nameValueList = _nameValueList;
@synthesize compatibilityNotes = _compatibilityNotes;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"NameValueList" propertyName:@"nameValueList" type:PICO_TYPE_OBJECT clazz:[Shopping_NameValueListType class]];
    [map setObject:ps forKey:@"nameValueList"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CompatibilityNotes" propertyName:@"compatibilityNotes" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"compatibilityNotes"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}




@end
