// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>

/**
 @file
 
 This enumerated type contains a partial list of ISO 3166 standard two-letter codes that represent countries around the world.
 <br><br>
 It is recommended that users use the <b>GeteBayDetails</b> call of the Trading API to see the full list of currently supported country codes,
 and the English names associated with each code (e.g., KY="Cayman Islands"). Call 
 <b>GeteBayDetails</b> with <b>DetailName</b> set to <b>Country</b>, and then look for <b>CountryDetails.Country</b> fields in the response.
 
 
 @ingroup ShoppingInterface
*/

/**
 
 Afghanistan.
 
*/
extern NSString *const Shopping_CountryCodeType_AF;

/**
 
 Albania.
 
*/
extern NSString *const Shopping_CountryCodeType_AL;

/**
 
 Algeria.
 
*/
extern NSString *const Shopping_CountryCodeType_DZ;

/**
 
 American Samoa.
 
*/
extern NSString *const Shopping_CountryCodeType_AS;

/**
 
 Andorra.
 
*/
extern NSString *const Shopping_CountryCodeType_AD;

/**
 
 Angola.
 
*/
extern NSString *const Shopping_CountryCodeType_AO;

/**
 
 Anguilla.
 
*/
extern NSString *const Shopping_CountryCodeType_AI;

/**
 
 Antarctica.
 
*/
extern NSString *const Shopping_CountryCodeType_AQ;

/**
 
 Antigua and Barbuda.
 
*/
extern NSString *const Shopping_CountryCodeType_AG;

/**
 
 Argentina.
 
*/
extern NSString *const Shopping_CountryCodeType_AR;

/**
 
 Armenia.
 
*/
extern NSString *const Shopping_CountryCodeType_AM;

/**
 
 Aruba.
 
*/
extern NSString *const Shopping_CountryCodeType_AW;

/**
 
 Australia.
 
*/
extern NSString *const Shopping_CountryCodeType_AU;

/**
 
 Austria.
 
*/
extern NSString *const Shopping_CountryCodeType_AT;

/**
 
 Azerbaijan.
 
*/
extern NSString *const Shopping_CountryCodeType_AZ;

/**
 
 Bahamas.
 
*/
extern NSString *const Shopping_CountryCodeType_BS;

/**
 
 Bahrain.
 
*/
extern NSString *const Shopping_CountryCodeType_BH;

/**
 
 Bangladesh.
 
*/
extern NSString *const Shopping_CountryCodeType_BD;

/**
 
 Barbados.
 
*/
extern NSString *const Shopping_CountryCodeType_BB;

/**
 
 Belarus.
 
*/
extern NSString *const Shopping_CountryCodeType_BY;

/**
 
 Belgium.
 
*/
extern NSString *const Shopping_CountryCodeType_BE;

/**
 
 Belize.
 
*/
extern NSString *const Shopping_CountryCodeType_BZ;

/**
 
 Benin.
 
*/
extern NSString *const Shopping_CountryCodeType_BJ;

/**
 
 Bermuda.
 
*/
extern NSString *const Shopping_CountryCodeType_BM;

/**
 
 Bhutan.
 
*/
extern NSString *const Shopping_CountryCodeType_BT;

/**
 
 Bolivia.
 
*/
extern NSString *const Shopping_CountryCodeType_BO;

/**
 
 Bosnia and Herzegovina.
 
*/
extern NSString *const Shopping_CountryCodeType_BA;

/**
 
 Botswana.
 
*/
extern NSString *const Shopping_CountryCodeType_BW;

/**
 
 Bouvet Island.
 
*/
extern NSString *const Shopping_CountryCodeType_BV;

/**
 
 Brazil.
 
*/
extern NSString *const Shopping_CountryCodeType_BR;

/**
 
 British Indian Ocean Territory.
 
*/
extern NSString *const Shopping_CountryCodeType_IO;

/**
 
 Brunei Darussalam.
 
*/
extern NSString *const Shopping_CountryCodeType_BN;

/**
 
 Bulgaria.
 
*/
extern NSString *const Shopping_CountryCodeType_BG;

/**
 
 Burkina Faso.
 
*/
extern NSString *const Shopping_CountryCodeType_BF;

/**
 
 Burundi.
 
*/
extern NSString *const Shopping_CountryCodeType_BI;

/**
 
 Cambodia.
 
*/
extern NSString *const Shopping_CountryCodeType_KH;

/**
 
 Cameroon.
 
*/
extern NSString *const Shopping_CountryCodeType_CM;

/**
 
 Canada.
 
*/
extern NSString *const Shopping_CountryCodeType_CA;

/**
 
 Cape Verde.
 
*/
extern NSString *const Shopping_CountryCodeType_CV;

/**
 
 Cayman Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_KY;

/**
 
 Central African Republic.
 
*/
extern NSString *const Shopping_CountryCodeType_CF;

/**
 
 Chad.
 
*/
extern NSString *const Shopping_CountryCodeType_TD;

/**
 
 Chile.
 
*/
extern NSString *const Shopping_CountryCodeType_CL;

/**
 
 China.
 
*/
extern NSString *const Shopping_CountryCodeType_CN;

/**
 
 Christmas Island.
 
*/
extern NSString *const Shopping_CountryCodeType_CX;

/**
 
 Cocos (Keeling) Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_CC;

/**
 
 Colombia.
 
*/
extern NSString *const Shopping_CountryCodeType_CO;

/**
 
 Comoros.
 
*/
extern NSString *const Shopping_CountryCodeType_KM;

/**
 
 Congo.
 
*/
extern NSString *const Shopping_CountryCodeType_CG;

/**
 
 The Democratic Republic of the Congo.
 
*/
extern NSString *const Shopping_CountryCodeType_CD;

/**
 
 Cook Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_CK;

/**
 
 Costa Rica.
 
*/
extern NSString *const Shopping_CountryCodeType_CR;

/**
 
 Cote d'Ivoire.
 
*/
extern NSString *const Shopping_CountryCodeType_CI;

/**
 
 Croatia.
 
*/
extern NSString *const Shopping_CountryCodeType_HR;

/**
 
 Cuba.
 
*/
extern NSString *const Shopping_CountryCodeType_CU;

/**
 
 Cyprus.
 
*/
extern NSString *const Shopping_CountryCodeType_CY;

/**
 
 Czech Republic.
 
*/
extern NSString *const Shopping_CountryCodeType_CZ;

/**
 
 Denmark.
 
*/
extern NSString *const Shopping_CountryCodeType_DK;

/**
 
 Djibouti.
 
*/
extern NSString *const Shopping_CountryCodeType_DJ;

/**
 
 Dominica.
 
*/
extern NSString *const Shopping_CountryCodeType_DM;

/**
 
 Dominican Republic.
 
*/
extern NSString *const Shopping_CountryCodeType_DO;

/**
 
 No longer in use.
 
*/
extern NSString *const Shopping_CountryCodeType_TP;

/**
 
 Ecuador.
 
*/
extern NSString *const Shopping_CountryCodeType_EC;

/**
 
 Egypt.
 
*/
extern NSString *const Shopping_CountryCodeType_EG;

/**
 
 El Salvador.
 
*/
extern NSString *const Shopping_CountryCodeType_SV;

/**
 
 Equatorial Guinea.
 
*/
extern NSString *const Shopping_CountryCodeType_GQ;

/**
 
 Eritrea.
 
*/
extern NSString *const Shopping_CountryCodeType_ER;

/**
 
 Estonia.
 
*/
extern NSString *const Shopping_CountryCodeType_EE;

/**
 
 Ethiopia.
 
*/
extern NSString *const Shopping_CountryCodeType_ET;

/**
 
 Falkland Islands (Malvinas).
 
*/
extern NSString *const Shopping_CountryCodeType_FK;

/**
 
 Faroe Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_FO;

/**
 
 Fiji.
 
*/
extern NSString *const Shopping_CountryCodeType_FJ;

/**
 
 Finland.
 
*/
extern NSString *const Shopping_CountryCodeType_FI;

/**
 
 France.
 
*/
extern NSString *const Shopping_CountryCodeType_FR;

/**
 
 French Guiana.
 
*/
extern NSString *const Shopping_CountryCodeType_GF;

/**
 
 French Polynesia. Includes Tahiti.
 
*/
extern NSString *const Shopping_CountryCodeType_PF;

/**
 
 French Southern Territories.
 
*/
extern NSString *const Shopping_CountryCodeType_TF;

/**
 
 Gabon.
 
*/
extern NSString *const Shopping_CountryCodeType_GA;

/**
 
 Gambia.
 
*/
extern NSString *const Shopping_CountryCodeType_GM;

/**
 
 Georgia.
 
*/
extern NSString *const Shopping_CountryCodeType_GE;

/**
 
 Germany.
 
*/
extern NSString *const Shopping_CountryCodeType_DE;

/**
 
 Ghana.
 
*/
extern NSString *const Shopping_CountryCodeType_GH;

/**
 
 Gibraltar.
 
*/
extern NSString *const Shopping_CountryCodeType_GI;

/**
 
 Greece.
 
*/
extern NSString *const Shopping_CountryCodeType_GR;

/**
 
 Greenland.
 
*/
extern NSString *const Shopping_CountryCodeType_GL;

/**
 
 Grenada.
 
*/
extern NSString *const Shopping_CountryCodeType_GD;

/**
 
 Guadeloupe.
 
*/
extern NSString *const Shopping_CountryCodeType_GP;

/**
 
 Guam.
 
*/
extern NSString *const Shopping_CountryCodeType_GU;

/**
 
 Guatemala.
 
*/
extern NSString *const Shopping_CountryCodeType_GT;

/**
 
 Guinea.
 
*/
extern NSString *const Shopping_CountryCodeType_GN;

/**
 
 Guinea-Bissau.
 
*/
extern NSString *const Shopping_CountryCodeType_GW;

/**
 
 Guyana.
 
*/
extern NSString *const Shopping_CountryCodeType_GY;

/**
 
 Haiti.
 
*/
extern NSString *const Shopping_CountryCodeType_HT;

/**
 
 Heard Island and McDonald Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_HM;

/**
 
 Holy See (Vatican City state).
 
*/
extern NSString *const Shopping_CountryCodeType_VA;

/**
 
 Honduras.
 
*/
extern NSString *const Shopping_CountryCodeType_HN;

/**
 
 Hong Kong.
 
*/
extern NSString *const Shopping_CountryCodeType_HK;

/**
 
 Hungary.
 
*/
extern NSString *const Shopping_CountryCodeType_HU;

/**
 
 Iceland.
 
*/
extern NSString *const Shopping_CountryCodeType_IS;

/**
 
 India.
 
*/
extern NSString *const Shopping_CountryCodeType_IN;

/**
 
 Indonesia.
 
*/
extern NSString *const Shopping_CountryCodeType_ID;

/**
 
 Islamic Republic of Iran.
 
*/
extern NSString *const Shopping_CountryCodeType_IR;

/**
 
 Iraq.
 
*/
extern NSString *const Shopping_CountryCodeType_IQ;

/**
 
 Ireland.
 
*/
extern NSString *const Shopping_CountryCodeType_IE;

/**
 
 Israel.
 
*/
extern NSString *const Shopping_CountryCodeType_IL;

/**
 
 Italy.
 
*/
extern NSString *const Shopping_CountryCodeType_IT;

/**
 
 Jamaica.
 
*/
extern NSString *const Shopping_CountryCodeType_JM;

/**
 
 Japan.
 
*/
extern NSString *const Shopping_CountryCodeType_JP;

/**
 
 Jordan.
 
*/
extern NSString *const Shopping_CountryCodeType_JO;

/**
 
 Kazakhstan.
 
*/
extern NSString *const Shopping_CountryCodeType_KZ;

/**
 
 Kenya.
 
*/
extern NSString *const Shopping_CountryCodeType_KE;

/**
 
 Kiribati.
 
*/
extern NSString *const Shopping_CountryCodeType_KI;

/**
 
 Democratic People's Republic of Korea.
 
*/
extern NSString *const Shopping_CountryCodeType_KP;

/**
 
 Republic of Korea.
 
*/
extern NSString *const Shopping_CountryCodeType_KR;

/**
 
 Kuwait.
 
*/
extern NSString *const Shopping_CountryCodeType_KW;

/**
 
 Kyrgyzstan.
 
*/
extern NSString *const Shopping_CountryCodeType_KG;

/**
 
 Lao People's Democratic Republic.
 
*/
extern NSString *const Shopping_CountryCodeType_LA;

/**
 
 Latvia.
 
*/
extern NSString *const Shopping_CountryCodeType_LV;

/**
 
 Lebanon.
 
*/
extern NSString *const Shopping_CountryCodeType_LB;

/**
 
 Lesotho.
 
*/
extern NSString *const Shopping_CountryCodeType_LS;

/**
 
 Liberia.
 
*/
extern NSString *const Shopping_CountryCodeType_LR;

/**
 
 Libyan Arab Jamahiriya.
 
*/
extern NSString *const Shopping_CountryCodeType_LY;

/**
 
 Liechtenstein.
 
*/
extern NSString *const Shopping_CountryCodeType_LI;

/**
 
 Lithuania.
 
*/
extern NSString *const Shopping_CountryCodeType_LT;

/**
 
 Luxembourg.
 
*/
extern NSString *const Shopping_CountryCodeType_LU;

/**
 
 Macao.
 
*/
extern NSString *const Shopping_CountryCodeType_MO;

/**
 
 The Former Yugoslav Republic of Macedonia.
 
*/
extern NSString *const Shopping_CountryCodeType_MK;

/**
 
 Madagascar.
 
*/
extern NSString *const Shopping_CountryCodeType_MG;

/**
 
 Malawi.
 
*/
extern NSString *const Shopping_CountryCodeType_MW;

/**
 
 Malaysia.
 
*/
extern NSString *const Shopping_CountryCodeType_MY;

/**
 
 Maldives.
 
*/
extern NSString *const Shopping_CountryCodeType_MV;

/**
 
 Mali.
 
*/
extern NSString *const Shopping_CountryCodeType_ML;

/**
 
 Malta.
 
*/
extern NSString *const Shopping_CountryCodeType_MT;

/**
 
 Marshall Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_MH;

/**
 
 Martinique.
 
*/
extern NSString *const Shopping_CountryCodeType_MQ;

/**
 
 Mauritania.
 
*/
extern NSString *const Shopping_CountryCodeType_MR;

/**
 
 Mauritius.
 
*/
extern NSString *const Shopping_CountryCodeType_MU;

/**
 
 Mayotte.
 
*/
extern NSString *const Shopping_CountryCodeType_YT;

/**
 
 Mexico.
 
*/
extern NSString *const Shopping_CountryCodeType_MX;

/**
 
 Federated States of Micronesia.
 
*/
extern NSString *const Shopping_CountryCodeType_FM;

/**
 
 Republic of Moldova.
 
*/
extern NSString *const Shopping_CountryCodeType_MD;

/**
 
 Monaco.
 
*/
extern NSString *const Shopping_CountryCodeType_MC;

/**
 
 Mongolia.
 
*/
extern NSString *const Shopping_CountryCodeType_MN;

/**
 
 Montserrat.
 
*/
extern NSString *const Shopping_CountryCodeType_MS;

/**
 
 Morocco.
 
*/
extern NSString *const Shopping_CountryCodeType_MA;

/**
 
 Mozambique.
 
*/
extern NSString *const Shopping_CountryCodeType_MZ;

/**
 
 Myanmar.
 
*/
extern NSString *const Shopping_CountryCodeType_MM;

/**
 
 Namibia.
 
*/
extern NSString *const Shopping_CountryCodeType_NA;

/**
 
 Nauru.
 
*/
extern NSString *const Shopping_CountryCodeType_NR;

/**
 
 Nepal.
 
*/
extern NSString *const Shopping_CountryCodeType_NP;

/**
 
 Netherlands.
 
*/
extern NSString *const Shopping_CountryCodeType_NL;

/**
 
 Netherlands Antilles.
 
*/
extern NSString *const Shopping_CountryCodeType_AN;

/**
 
 New Caledonia.
 
*/
extern NSString *const Shopping_CountryCodeType_NC;

/**
 
 New Zealand.
 
*/
extern NSString *const Shopping_CountryCodeType_NZ;

/**
 
 Nicaragua.
 
*/
extern NSString *const Shopping_CountryCodeType_NI;

/**
 
 Niger.
 
*/
extern NSString *const Shopping_CountryCodeType_NE;

/**
 
 Nigeria.
 
*/
extern NSString *const Shopping_CountryCodeType_NG;

/**
 
 Niue.
 
*/
extern NSString *const Shopping_CountryCodeType_NU;

/**
 
 Norfolk Island.
 
*/
extern NSString *const Shopping_CountryCodeType_NF;

/**
 
 Northern Mariana Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_MP;

/**
 
 Norway.
 
*/
extern NSString *const Shopping_CountryCodeType_NO;

/**
 
 Oman.
 
*/
extern NSString *const Shopping_CountryCodeType_OM;

/**
 
 Pakistan.
 
*/
extern NSString *const Shopping_CountryCodeType_PK;

/**
 
 Palau.
 
*/
extern NSString *const Shopping_CountryCodeType_PW;

/**
 
 Palestinian territory, Occupied.
 
*/
extern NSString *const Shopping_CountryCodeType_PS;

/**
 
 Panama.
 
*/
extern NSString *const Shopping_CountryCodeType_PA;

/**
 
 Papua New Guinea.
 
*/
extern NSString *const Shopping_CountryCodeType_PG;

/**
 
 Paraguay.
 
*/
extern NSString *const Shopping_CountryCodeType_PY;

/**
 
 Peru.
 
*/
extern NSString *const Shopping_CountryCodeType_PE;

/**
 
 Philippines.
 
*/
extern NSString *const Shopping_CountryCodeType_PH;

/**
 
 Pitcairn.
 
*/
extern NSString *const Shopping_CountryCodeType_PN;

/**
 
 Poland.
 
*/
extern NSString *const Shopping_CountryCodeType_PL;

/**
 
 Portugal.
 
*/
extern NSString *const Shopping_CountryCodeType_PT;

/**
 
 Puerto Rico.
 
*/
extern NSString *const Shopping_CountryCodeType_PR;

/**
 
 Qatar.
 
*/
extern NSString *const Shopping_CountryCodeType_QA;

/**
 
 Reunion.
 
*/
extern NSString *const Shopping_CountryCodeType_RE;

/**
 
 Romania.
 
*/
extern NSString *const Shopping_CountryCodeType_RO;

/**
 
 Russian Federation.
 
*/
extern NSString *const Shopping_CountryCodeType_RU;

/**
 
 Rwanda.
 
*/
extern NSString *const Shopping_CountryCodeType_RW;

/**
 
 Saint Helena.
 
*/
extern NSString *const Shopping_CountryCodeType_SH;

/**
 
 Saint Kitts and Nevis.
 
*/
extern NSString *const Shopping_CountryCodeType_KN;

/**
 
 Saint Lucia.
 
*/
extern NSString *const Shopping_CountryCodeType_LC;

/**
 
 Saint Pierre and Miquelon.
 
*/
extern NSString *const Shopping_CountryCodeType_PM;

/**
 
 Saint Vincent and the Grenadines.
 
*/
extern NSString *const Shopping_CountryCodeType_VC;

/**
 
 Samoa.
 
*/
extern NSString *const Shopping_CountryCodeType_WS;

/**
 
 San Marino.
 
*/
extern NSString *const Shopping_CountryCodeType_SM;

/**
 
 Sao Tome and Principe.
 
*/
extern NSString *const Shopping_CountryCodeType_ST;

/**
 
 Saudi Arabia.
 
*/
extern NSString *const Shopping_CountryCodeType_SA;

/**
 
 Senegal.
 
*/
extern NSString *const Shopping_CountryCodeType_SN;

/**
 
 Seychelles.
 
*/
extern NSString *const Shopping_CountryCodeType_SC;

/**
 
 Sierra Leone.
 
*/
extern NSString *const Shopping_CountryCodeType_SL;

/**
 
 Singapore.
 
*/
extern NSString *const Shopping_CountryCodeType_SG;

/**
 
 Slovakia.
 
*/
extern NSString *const Shopping_CountryCodeType_SK;

/**
 
 Slovenia.
 
*/
extern NSString *const Shopping_CountryCodeType_SI;

/**
 
 Solomon Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_SB;

/**
 
 Somalia.
 
*/
extern NSString *const Shopping_CountryCodeType_SO;

/**
 
 South Africa.
 
*/
extern NSString *const Shopping_CountryCodeType_ZA;

/**
 
 South Georgia and the South Sandwich Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_GS;

/**
 
 Spain.
 
*/
extern NSString *const Shopping_CountryCodeType_ES;

/**
 
 Sri Lanka.
 
*/
extern NSString *const Shopping_CountryCodeType_LK;

/**
 
 Sudan.
 
*/
extern NSString *const Shopping_CountryCodeType_SD;

/**
 
 Suriname.
 
*/
extern NSString *const Shopping_CountryCodeType_SR;

/**
 
 Svalbard and Jan Mayen.
 
*/
extern NSString *const Shopping_CountryCodeType_SJ;

/**
 
 Swaziland.
 
*/
extern NSString *const Shopping_CountryCodeType_SZ;

/**
 
 Sweden.
 
*/
extern NSString *const Shopping_CountryCodeType_SE;

/**
 
 Switzerland.
 
*/
extern NSString *const Shopping_CountryCodeType_CH;

/**
 
 Syrian Arab Republic.
 
*/
extern NSString *const Shopping_CountryCodeType_SY;

/**
 
 Taiwan, Province of China.
 
*/
extern NSString *const Shopping_CountryCodeType_TW;

/**
 
 Tajikistan.
 
*/
extern NSString *const Shopping_CountryCodeType_TJ;

/**
 
 Tanzania, United Republic of.
 
*/
extern NSString *const Shopping_CountryCodeType_TZ;

/**
 
 Thailand.
 
*/
extern NSString *const Shopping_CountryCodeType_TH;

/**
 
 Togo.
 
*/
extern NSString *const Shopping_CountryCodeType_TG;

/**
 
 Tokelau.
 
*/
extern NSString *const Shopping_CountryCodeType_TK;

/**
 
 Tonga.
 
*/
extern NSString *const Shopping_CountryCodeType_TO;

/**
 
 Trinidad and Tobago.
 
*/
extern NSString *const Shopping_CountryCodeType_TT;

/**
 
 Tunisia.
 
*/
extern NSString *const Shopping_CountryCodeType_TN;

/**
 
 Turkey.
 
*/
extern NSString *const Shopping_CountryCodeType_TR;

/**
 
 Turkmenistan.
 
*/
extern NSString *const Shopping_CountryCodeType_TM;

/**
 
 Turks and Caicos Islands.
 
*/
extern NSString *const Shopping_CountryCodeType_TC;

/**
 
 Tuvalu.
 
*/
extern NSString *const Shopping_CountryCodeType_TV;

/**
 
 Uganda.
 
*/
extern NSString *const Shopping_CountryCodeType_UG;

/**
 
 Ukraine.
 
*/
extern NSString *const Shopping_CountryCodeType_UA;

/**
 
 United Arab Emirates.
 
*/
extern NSString *const Shopping_CountryCodeType_AE;

/**
 
 United Kingdom.
 
*/
extern NSString *const Shopping_CountryCodeType_GB;

/**
 
 United States.
 
*/
extern NSString *const Shopping_CountryCodeType_US;

/**
 
 NOTE: United States Minor Outlying Islands was
 defined in the eBay list previously
 but is no longer a viable option. This country
 will remain on eBay country list for backward
 compatibility. Use 'US' instead.
 
*/
extern NSString *const Shopping_CountryCodeType_UM;

/**
 
 Uruguay.
 
*/
extern NSString *const Shopping_CountryCodeType_UY;

/**
 
 Uzbekistan.
 
*/
extern NSString *const Shopping_CountryCodeType_UZ;

/**
 
 Vanuatu.
 
*/
extern NSString *const Shopping_CountryCodeType_VU;

/**
 
 Venezuela.
 
*/
extern NSString *const Shopping_CountryCodeType_VE;

/**
 
 Vietnam.
 
*/
extern NSString *const Shopping_CountryCodeType_VN;

/**
 
 Virgin Islands, British.
 
*/
extern NSString *const Shopping_CountryCodeType_VG;

/**
 
 Virgin Islands, U.S.
 
*/
extern NSString *const Shopping_CountryCodeType_VI;

/**
 
 Wallis and Futuna.
 
*/
extern NSString *const Shopping_CountryCodeType_WF;

/**
 
 Western Sahara.
 
*/
extern NSString *const Shopping_CountryCodeType_EH;

/**
 
 Yemen.
 
*/
extern NSString *const Shopping_CountryCodeType_YE;

/**
 
 No longer in use. See RS for Serbia and ME for Montenegro.
 
*/
extern NSString *const Shopping_CountryCodeType_YU;

/**
 
 Zambia.
 
*/
extern NSString *const Shopping_CountryCodeType_ZM;

/**
 
 Zimbabwe.
 
*/
extern NSString *const Shopping_CountryCodeType_ZW;

/**
 
 NOTE: APO/FPO was defined in eBay list previously
 but they are not defined in ISO 3166. This country
 will remain on eBay country code list for backward
 compatibility.
  
*/
extern NSString *const Shopping_CountryCodeType_AA;

/**
 
 NOTE: Guernsey was defined in eBay list previously
 but they are not defined in ISO 3166. This country
 will remain on eBay country list for backward
 compatibility.
  
*/
extern NSString *const Shopping_CountryCodeType_QM;

/**
 
  NOTE: Jan Mayen was defined in eBay list previously
  but they are not defined in ISO 3166. This country
  will remain on eBay country list for backward
  compatibility.
  
*/
extern NSString *const Shopping_CountryCodeType_QN;

/**
 
  NOTE: Jersey was defined in eBay list previously
  but they are not defined in ISO 3166. This country
  will remain on eBay country list for backward
  compatibility.
  
*/
extern NSString *const Shopping_CountryCodeType_QO;

extern NSString *const Shopping_CountryCodeType_QP;

/**
 
 Placeholder value. See
 <a href="http://developer.ebay.com/DevZone/shopping/docs/CallRef/types/simpleTypes.html#token">token</a>.
 
*/
extern NSString *const Shopping_CountryCodeType_CUSTOM_CODE;
