// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_ShippingCostSummaryType.h"
#import "Shopping_AmountType.h"

@implementation Shopping_ShippingCostSummaryType

@synthesize shippingServiceName = _shippingServiceName;
@synthesize shippingServiceCost = _shippingServiceCost;
@synthesize insuranceCost = _insuranceCost;
@synthesize shippingType = _shippingType;
@synthesize localPickup = _localPickup;
@synthesize insuranceOption = _insuranceOption;
@synthesize listedShippingServiceCost = _listedShippingServiceCost;
@synthesize importCharge = _importCharge;
@synthesize logisticPlanType = _logisticPlanType;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingServiceName" propertyName:@"shippingServiceName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"shippingServiceName"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingServiceCost" propertyName:@"shippingServiceCost" type:PICO_TYPE_OBJECT clazz:[Shopping_AmountType class]];
    [map setObject:ps forKey:@"shippingServiceCost"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"InsuranceCost" propertyName:@"insuranceCost" type:PICO_TYPE_OBJECT clazz:[Shopping_AmountType class]];
    [map setObject:ps forKey:@"insuranceCost"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingType" propertyName:@"shippingType" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"shippingType"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LocalPickup" propertyName:@"localPickup" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"localPickup"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"InsuranceOption" propertyName:@"insuranceOption" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"insuranceOption"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ListedShippingServiceCost" propertyName:@"listedShippingServiceCost" type:PICO_TYPE_OBJECT clazz:[Shopping_AmountType class]];
    [map setObject:ps forKey:@"listedShippingServiceCost"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ImportCharge" propertyName:@"importCharge" type:PICO_TYPE_OBJECT clazz:[Shopping_AmountType class]];
    [map setObject:ps forKey:@"importCharge"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LogisticPlanType" propertyName:@"logisticPlanType" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"logisticPlanType"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}




@end
