// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Shopping_ReviewSortCodeType.h"


/**
 
 Sorts reviews by creation time, in ascending or descending order.
 
*/
NSString *const Shopping_ReviewSortCodeType_CREATION_TIME = @"CreationTime";

/**
 
 Reserved for values that are not available in the version of the schema
 you are using. This means if in a newer version of the API eBay adds a new 
 value to <b>ProductSortCodeList</b> type and the request was using 
 a <i>lower</i> version, 'CustomCode' is returned instead of the 
 new value.
 
*/
NSString *const Shopping_ReviewSortCodeType_CUSTOM_CODE = @"CustomCode";
