// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_GetShippingCostsResponseType.h"
#import "Shopping_ShippingDetailsType.h"
#import "Shopping_PickUpInStoreDetailsType.h"
#import "Shopping_ShippingCostSummaryType.h"

@implementation Shopping_GetShippingCostsResponseType

@synthesize shippingDetails = _shippingDetails;
@synthesize shippingCostSummary = _shippingCostSummary;
@synthesize pickUpInStoreDetails = _pickUpInStoreDetails;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GetShippingCostsResponse" nsUri:@"urn:ebay:apis:eBLBaseComponents"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingDetails" propertyName:@"shippingDetails" type:PICO_TYPE_OBJECT clazz:[Shopping_ShippingDetailsType class]];
    [map setObject:ps forKey:@"shippingDetails"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingCostSummary" propertyName:@"shippingCostSummary" type:PICO_TYPE_OBJECT clazz:[Shopping_ShippingCostSummaryType class]];
    [map setObject:ps forKey:@"shippingCostSummary"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PickUpInStoreDetails" propertyName:@"pickUpInStoreDetails" type:PICO_TYPE_OBJECT clazz:[Shopping_PickUpInStoreDetailsType class]];
    [map setObject:ps forKey:@"pickUpInStoreDetails"];
    
    return map;
}




@end
