// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_ErrorType.h"
#import "Shopping_ErrorParameterType.h"

@implementation Shopping_ErrorType

@synthesize shortMessage = _shortMessage;
@synthesize longMessage = _longMessage;
@synthesize errorCode = _errorCode;
@synthesize userDisplayHint = _userDisplayHint;
@synthesize severityCode = _severityCode;
@synthesize errorParameters = _errorParameters;
@synthesize errorClassification = _errorClassification;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShortMessage" propertyName:@"shortMessage" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"shortMessage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LongMessage" propertyName:@"longMessage" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"longMessage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ErrorCode" propertyName:@"errorCode" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"errorCode"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserDisplayHint" propertyName:@"userDisplayHint" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"userDisplayHint"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SeverityCode" propertyName:@"severityCode" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"severityCode"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ErrorParameters" propertyName:@"errorParameters" type:PICO_TYPE_OBJECT clazz:[Shopping_ErrorParameterType class]];
    [map setObject:ps forKey:@"errorParameters"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ErrorClassification" propertyName:@"errorClassification" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"errorClassification"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}




@end
