// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_ShippingServiceOptionType.h"
#import "Shopping_AmountType.h"

@implementation Shopping_ShippingServiceOptionType

@synthesize shippingInsuranceCost = _shippingInsuranceCost;
@synthesize shippingServiceName = _shippingServiceName;
@synthesize logisticPlanType = _logisticPlanType;
@synthesize shippingServiceCost = _shippingServiceCost;
@synthesize shippingServiceAdditionalCost = _shippingServiceAdditionalCost;
@synthesize shippingServicePriority = _shippingServicePriority;
@synthesize expeditedService = _expeditedService;
@synthesize shippingTimeMin = _shippingTimeMin;
@synthesize shippingTimeMax = _shippingTimeMax;
@synthesize shippingSurcharge = _shippingSurcharge;
@synthesize shipsTo = _shipsTo;
@synthesize estimatedDeliveryMinTime = _estimatedDeliveryMinTime;
@synthesize estimatedDeliveryMaxTime = _estimatedDeliveryMaxTime;
@synthesize fastAndFree = _fastAndFree;
@synthesize shippingServiceCutOffTime = _shippingServiceCutOffTime;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingInsuranceCost" propertyName:@"shippingInsuranceCost" type:PICO_TYPE_OBJECT clazz:[Shopping_AmountType class]];
    [map setObject:ps forKey:@"shippingInsuranceCost"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingServiceName" propertyName:@"shippingServiceName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"shippingServiceName"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LogisticPlanType" propertyName:@"logisticPlanType" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"logisticPlanType"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingServiceCost" propertyName:@"shippingServiceCost" type:PICO_TYPE_OBJECT clazz:[Shopping_AmountType class]];
    [map setObject:ps forKey:@"shippingServiceCost"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingServiceAdditionalCost" propertyName:@"shippingServiceAdditionalCost" type:PICO_TYPE_OBJECT clazz:[Shopping_AmountType class]];
    [map setObject:ps forKey:@"shippingServiceAdditionalCost"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingServicePriority" propertyName:@"shippingServicePriority" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"shippingServicePriority"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ExpeditedService" propertyName:@"expeditedService" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"expeditedService"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingTimeMin" propertyName:@"shippingTimeMin" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"shippingTimeMin"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingTimeMax" propertyName:@"shippingTimeMax" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"shippingTimeMax"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingSurcharge" propertyName:@"shippingSurcharge" type:PICO_TYPE_OBJECT clazz:[Shopping_AmountType class]];
    [map setObject:ps forKey:@"shippingSurcharge"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"ShipsTo" propertyName:@"shipsTo" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"shipsTo"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"EstimatedDeliveryMinTime" propertyName:@"estimatedDeliveryMinTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"estimatedDeliveryMinTime"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"EstimatedDeliveryMaxTime" propertyName:@"estimatedDeliveryMaxTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"estimatedDeliveryMaxTime"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FastAndFree" propertyName:@"fastAndFree" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"fastAndFree"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ShippingServiceCutOffTime" propertyName:@"shippingServiceCutOffTime" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"shippingServiceCutOffTime"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}




@end
