// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_CharityType.h"

@implementation Shopping_CharityType

@synthesize charityID = _charityID;
@synthesize charityName = _charityName;
@synthesize charityNumber = _charityNumber;
@synthesize donationPercent = _donationPercent;
@synthesize mission = _mission;
@synthesize logoURL = _logoURL;
@synthesize charityListing = _charityListing;
@synthesize status = _status;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CharityID" propertyName:@"charityID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"charityID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CharityName" propertyName:@"charityName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"charityName"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CharityNumber" propertyName:@"charityNumber" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"charityNumber"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"DonationPercent" propertyName:@"donationPercent" type:PICO_TYPE_FLOAT clazz:nil];
    [map setObject:ps forKey:@"donationPercent"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Mission" propertyName:@"mission" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"mission"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LogoURL" propertyName:@"logoURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"logoURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CharityListing" propertyName:@"charityListing" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"charityListing"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Status" propertyName:@"status" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"status"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}




@end
