// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Shopping_AmountType;

/**
 
 Contains various details about the current status of a listing. These
 values are computed by eBay and cannot be specified at listing time.
 
 
 @ingroup ShoppingInterface
*/
@interface Shopping_SellingStatusType : NSObject <PicoBindable> {

@private
    Shopping_AmountType *_convertedCurrentPrice;
    Shopping_AmountType *_currentPrice;
    NSNumber *_quantitySold;
    NSNumber *_quantitySoldByPickupInStore;
    NSMutableArray *_any;

}


/**
 
 Not used. See Item.ConvertedCurrentPrice.
 
 
 type : class Shopping_AmountType
*/
@property (nonatomic, strong) Shopping_AmountType *convertedCurrentPrice;

/**
 
 Not used. See Item.CurrentPrice and Variation.StartPrice.
 
 
 type : class Shopping_AmountType
*/
@property (nonatomic, strong) Shopping_AmountType *currentPrice;

/**
 
 The number of items sold from this variation. Subtract from
 Quantity to determine the number of items available.
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, strong) NSNumber *quantitySold;

/**
 
 This field indicates the total quantity of that corresponding item variation (for example, large blue shirts) sold and picked up by buyers using the In-Store Pickup option. This value is the total quantity of this item variation purchased by one or more buyers using the In-Store Pickup option, and is not the total number of In-Store Pickup orders for that item variation. So, if two buyers selected the In-Store Pickup option, but each of these buyers bought a quantity of five of these item variations (in same purchase), the <b>Item.Variations.Variation.SellingStatus.QuantitySoldByPickupInStore</b> value would be '10' and not '2'. 
 <br>
 <br>
 This field will only be returned if the listing is eligible for In-Store Pickup. 
 <br/><br/>
 <span class="tablenote">
 <strong>Note:</strong> At this time, the In-Store Pickup feature is generally only available to large retail merchants, and can only be applied to multi-quantity, fixed-price listings. 
 </span>
 
 
 type : NSNumber, wrapper for primitive int
*/
@property (nonatomic, strong) NSNumber *quantitySoldByPickupInStore;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, strong) NSMutableArray *any;


@end
