// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Shopping_SimpleUserType.h"

@implementation Shopping_SimpleUserType

@synthesize userID = _userID;
@synthesize feedbackPrivate = _feedbackPrivate;
@synthesize feedbackRatingStar = _feedbackRatingStar;
@synthesize feedbackScore = _feedbackScore;
@synthesize userAnonymized = _userAnonymized;
@synthesize ebayNewUser = _newUser;
@synthesize registrationDate = _registrationDate;
@synthesize registrationSite = _registrationSite;
@synthesize status = _status;
@synthesize sellerBusinessType = _sellerBusinessType;
@synthesize storeURL = _storeURL;
@synthesize storeName = _storeName;
@synthesize sellerItemsURL = _sellerItemsURL;
@synthesize aboutMeURL = _aboutMeURL;
@synthesize myWorldURL = _myWorldURL;
@synthesize myWorldSmallImage = _myWorldSmallImage;
@synthesize myWorldLargeImage = _myWorldLargeImage;
@synthesize reviewsAndGuidesURL = _reviewsAndGuidesURL;
@synthesize feedbackDetailsURL = _feedbackDetailsURL;
@synthesize positiveFeedbackPercent = _positiveFeedbackPercent;
@synthesize sellerLevel = _sellerLevel;
@synthesize topRatedSeller = _topRatedSeller;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserID" propertyName:@"userID" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"userID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FeedbackPrivate" propertyName:@"feedbackPrivate" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"feedbackPrivate"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FeedbackRatingStar" propertyName:@"feedbackRatingStar" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"feedbackRatingStar"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FeedbackScore" propertyName:@"feedbackScore" type:PICO_TYPE_INT clazz:nil];
    [map setObject:ps forKey:@"feedbackScore"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"UserAnonymized" propertyName:@"userAnonymized" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"userAnonymized"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NewUser" propertyName:@"newUser" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"newUser"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RegistrationDate" propertyName:@"registrationDate" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"registrationDate"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"RegistrationSite" propertyName:@"registrationSite" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"registrationSite"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Status" propertyName:@"status" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"status"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SellerBusinessType" propertyName:@"sellerBusinessType" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"sellerBusinessType"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"StoreURL" propertyName:@"storeURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"storeURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"StoreName" propertyName:@"storeName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"storeName"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SellerItemsURL" propertyName:@"sellerItemsURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"sellerItemsURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"AboutMeURL" propertyName:@"aboutMeURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"aboutMeURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MyWorldURL" propertyName:@"myWorldURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"myWorldURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MyWorldSmallImage" propertyName:@"myWorldSmallImage" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"myWorldSmallImage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MyWorldLargeImage" propertyName:@"myWorldLargeImage" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"myWorldLargeImage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ReviewsAndGuidesURL" propertyName:@"reviewsAndGuidesURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"reviewsAndGuidesURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"FeedbackDetailsURL" propertyName:@"feedbackDetailsURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"feedbackDetailsURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PositiveFeedbackPercent" propertyName:@"positiveFeedbackPercent" type:PICO_TYPE_FLOAT clazz:nil];
    [map setObject:ps forKey:@"positiveFeedbackPercent"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SellerLevel" propertyName:@"sellerLevel" type:PICO_TYPE_ENUM clazz:nil];
    [map setObject:ps forKey:@"sellerLevel"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TopRatedSeller" propertyName:@"topRatedSeller" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"topRatedSeller"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}




@end
