// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Request;
@class BrowseNode;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface BrowseNodes : NSObject <PicoBindable> {

@private
    Request *_request;
    NSMutableArray *_browseNode;

}


/**
 (public property)
 
 type : class Request
*/
@property (nonatomic, strong) Request *request;

/**
 (public property)
 
 entry type : class BrowseNode
*/

@property (nonatomic, strong) NSMutableArray *browseNode;


@end
