// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class TopSellers;
@class Price;
@class Request;
@class NewReleases;
@class OtherCategoriesSimilarProducts;
@class CartItems;
@class SavedForLaterItems;
@class SimilarViewedProducts;
@class SimilarProducts;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface Cart : NSObject <PicoBindable> {

@private
    Request *_request;
    NSString *_cartId;
    NSString *_hmac;
    NSString *_urlEncodedHMAC;
    NSString *_purchaseURL;
    NSString *_mobileCartURL;
    Price *_subTotal;
    CartItems *_cartItems;
    SavedForLaterItems *_savedForLaterItems;
    SimilarProducts *_similarProducts;
    TopSellers *_topSellers;
    NewReleases *_newReleases;
    SimilarViewedProducts *_similarViewedProducts;
    OtherCategoriesSimilarProducts *_otherCategoriesSimilarProducts;

}


/**
 (public property)
 
 type : class Request
*/
@property (nonatomic, strong) Request *request;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *cartId;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *hmac;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *urlEncodedHMAC;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *purchaseURL;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *mobileCartURL;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *subTotal;

/**
 (public property)
 
 type : class CartItems
*/
@property (nonatomic, strong) CartItems *cartItems;

/**
 (public property)
 
 type : class SavedForLaterItems
*/
@property (nonatomic, strong) SavedForLaterItems *savedForLaterItems;

/**
 (public property)
 
 type : class SimilarProducts
*/
@property (nonatomic, strong) SimilarProducts *similarProducts;

/**
 (public property)
 
 type : class TopSellers
*/
@property (nonatomic, strong) TopSellers *topSellers;

/**
 (public property)
 
 type : class NewReleases
*/
@property (nonatomic, strong) NewReleases *amazonNewReleases;

/**
 (public property)
 
 type : class SimilarViewedProducts
*/
@property (nonatomic, strong) SimilarViewedProducts *similarViewedProducts;

/**
 (public property)
 
 type : class OtherCategoriesSimilarProducts
*/
@property (nonatomic, strong) OtherCategoriesSimilarProducts *otherCategoriesSimilarProducts;


@end
