// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Offer;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface Offers : NSObject <PicoBindable> {

@private
    NSNumber *_totalOffers;
    NSNumber *_totalOfferPages;
    NSString *_moreOffersUrl;
    NSMutableArray *_offer;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *totalOffers;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *totalOfferPages;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *moreOffersUrl;

/**
 (public property)
 
 entry type : class Offer
*/

@property (nonatomic, strong) NSMutableArray *offer;


@end
