// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "OfferSummary.h"
#import "Price.h"

@implementation OfferSummary

@synthesize lowestNewPrice = _lowestNewPrice;
@synthesize lowestUsedPrice = _lowestUsedPrice;
@synthesize lowestCollectiblePrice = _lowestCollectiblePrice;
@synthesize lowestRefurbishedPrice = _lowestRefurbishedPrice;
@synthesize totalNew = _totalNew;
@synthesize totalUsed = _totalUsed;
@synthesize totalCollectible = _totalCollectible;
@synthesize totalRefurbished = _totalRefurbished;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"OfferSummary" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LowestNewPrice" propertyName:@"lowestNewPrice" type:PICO_TYPE_OBJECT clazz:[Price class]];
    [map setObject:ps forKey:@"lowestNewPrice"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LowestUsedPrice" propertyName:@"lowestUsedPrice" type:PICO_TYPE_OBJECT clazz:[Price class]];
    [map setObject:ps forKey:@"lowestUsedPrice"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LowestCollectiblePrice" propertyName:@"lowestCollectiblePrice" type:PICO_TYPE_OBJECT clazz:[Price class]];
    [map setObject:ps forKey:@"lowestCollectiblePrice"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LowestRefurbishedPrice" propertyName:@"lowestRefurbishedPrice" type:PICO_TYPE_OBJECT clazz:[Price class]];
    [map setObject:ps forKey:@"lowestRefurbishedPrice"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalNew" propertyName:@"totalNew" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"totalNew"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalUsed" propertyName:@"totalUsed" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"totalUsed"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalCollectible" propertyName:@"totalCollectible" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"totalCollectible"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalRefurbished" propertyName:@"totalRefurbished" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"totalRefurbished"];
    
    return map;
}




@end
