// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Errors;
@class HTTPHeaders;
@class Arguments;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface OperationRequest : NSObject <PicoBindable> {

@private
    HTTPHeaders *_httpHeaders;
    NSString *_requestId;
    Arguments *_arguments;
    Errors *_errors;
    NSNumber *_requestProcessingTime;

}


/**
 (public property)
 
 type : class HTTPHeaders
*/
@property (nonatomic, strong) HTTPHeaders *httpHeaders;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *requestId;

/**
 (public property)
 
 type : class Arguments
*/
@property (nonatomic, strong) Arguments *arguments;

/**
 (public property)
 
 type : class Errors
*/
@property (nonatomic, strong) Errors *errors;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive float
*/
@property (nonatomic, strong) NSNumber *requestProcessingTime;


@end
