// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "TopItemSet.h"
#import "TopItem.h"

@implementation TopItemSet

@synthesize type = _type;
@synthesize topItem = _topItem;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"TopItemSet" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Type" propertyName:@"type" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"type"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"TopItem" propertyName:@"topItem" type:PICO_TYPE_OBJECT clazz:[TopItem class]];
    [map setObject:ps forKey:@"topItem"];
    
    return map;
}




@end
