// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Variations.h"
#import "Item.h"
#import "VariationDimensions.h"

@implementation Variations

@synthesize totalVariations = _totalVariations;
@synthesize totalVariationPages = _totalVariationPages;
@synthesize variationDimensions = _variationDimensions;
@synthesize item = _item;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"Variations" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalVariations" propertyName:@"totalVariations" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"totalVariations"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TotalVariationPages" propertyName:@"totalVariationPages" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"totalVariationPages"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"VariationDimensions" propertyName:@"variationDimensions" type:PICO_TYPE_OBJECT clazz:[VariationDimensions class]];
    [map setObject:ps forKey:@"variationDimensions"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"Item" propertyName:@"item" type:PICO_TYPE_OBJECT clazz:[Item class]];
    [map setObject:ps forKey:@"item"];
    
    return map;
}




@end
