// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "MetaData.h"
#import "KeyValuePair.h"

@implementation MetaData

@synthesize keyValuePair = _keyValuePair;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"KeyValuePair" propertyName:@"keyValuePair" type:PICO_TYPE_OBJECT clazz:[KeyValuePair class]];
    [map setObject:ps forKey:@"keyValuePair"];
    
    return map;
}




@end
