// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Finding_Affiliate.h"

@implementation Finding_Affiliate

@synthesize trackingId = _trackingId;
@synthesize networkId = _networkId;
@synthesize customId = _customId;
@synthesize geoTargeting = _geoTargeting;
@synthesize delimiter = _delimiter;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"trackingId" propertyName:@"trackingId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"trackingId"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"networkId" propertyName:@"networkId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"networkId"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"customId" propertyName:@"customId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"customId"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"geoTargeting" propertyName:@"geoTargeting" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"geoTargeting"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"delimiter" propertyName:@"delimiter" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"delimiter"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}




@end
