// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Finding_SearchItem.h"
#import "Finding_Condition.h"
#import "Finding_SellerInfo.h"
#import "Finding_UnitPriceInfo.h"
#import "Finding_Storefront.h"
#import "Finding_SellingStatus.h"
#import "Finding_DiscountPriceInfo.h"
#import "Finding_ListingInfo.h"
#import "Finding_Distance.h"
#import "Finding_GalleryInfoContainer.h"
#import "Finding_Category.h"
#import "Finding_ShippingInfo.h"
#import "Finding_ItemAttribute.h"
#import "Finding_ProductId.h"

@implementation Finding_SearchItem

@synthesize itemId = _itemId;
@synthesize title = _title;
@synthesize globalId = _globalId;
@synthesize subtitle = _subtitle;
@synthesize primaryCategory = _primaryCategory;
@synthesize secondaryCategory = _secondaryCategory;
@synthesize galleryURL = _galleryURL;
@synthesize galleryInfoContainer = _galleryInfoContainer;
@synthesize viewItemURL = _viewItemURL;
@synthesize charityId = _charityId;
@synthesize productId = _productId;
@synthesize paymentMethod = _paymentMethod;
@synthesize autoPay = _autoPay;
@synthesize postalCode = _postalCode;
@synthesize location = _location;
@synthesize country = _country;
@synthesize storeInfo = _storeInfo;
@synthesize sellerInfo = _sellerInfo;
@synthesize shippingInfo = _shippingInfo;
@synthesize sellingStatus = _sellingStatus;
@synthesize listingInfo = _listingInfo;
@synthesize returnsAccepted = _returnsAccepted;
@synthesize galleryPlusPictureURL = _galleryPlusPictureURL;
@synthesize compatibility = _compatibility;
@synthesize distance = _distance;
@synthesize condition = _condition;
@synthesize isMultiVariationListing = _isMultiVariationListing;
@synthesize discountPriceInfo = _discountPriceInfo;
@synthesize pictureURLSuperSize = _pictureURLSuperSize;
@synthesize pictureURLLarge = _pictureURLLarge;
@synthesize unitPrice = _unitPrice;
@synthesize attribute = _attribute;
@synthesize topRatedListing = _topRatedListing;
@synthesize delimiter = _delimiter;
@synthesize any = _any;
@synthesize eekStatus = _eekStatus;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"itemId" propertyName:@"itemId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"itemId"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"title" propertyName:@"title" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"title"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"globalId" propertyName:@"globalId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"globalId"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"subtitle" propertyName:@"subtitle" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"subtitle"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"primaryCategory" propertyName:@"primaryCategory" type:PICO_TYPE_OBJECT clazz:[Finding_Category class]];
    [map setObject:ps forKey:@"primaryCategory"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"secondaryCategory" propertyName:@"secondaryCategory" type:PICO_TYPE_OBJECT clazz:[Finding_Category class]];
    [map setObject:ps forKey:@"secondaryCategory"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"galleryURL" propertyName:@"galleryURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"galleryURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"galleryInfoContainer" propertyName:@"galleryInfoContainer" type:PICO_TYPE_OBJECT clazz:[Finding_GalleryInfoContainer class]];
    [map setObject:ps forKey:@"galleryInfoContainer"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"viewItemURL" propertyName:@"viewItemURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"viewItemURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"charityId" propertyName:@"charityId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"charityId"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"productId" propertyName:@"productId" type:PICO_TYPE_OBJECT clazz:[Finding_ProductId class]];
    [map setObject:ps forKey:@"productId"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"paymentMethod" propertyName:@"paymentMethod" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"paymentMethod"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"autoPay" propertyName:@"autoPay" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"autoPay"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"postalCode" propertyName:@"postalCode" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"postalCode"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"location" propertyName:@"location" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"location"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"country" propertyName:@"country" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"country"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"storeInfo" propertyName:@"storeInfo" type:PICO_TYPE_OBJECT clazz:[Finding_Storefront class]];
    [map setObject:ps forKey:@"storeInfo"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"sellerInfo" propertyName:@"sellerInfo" type:PICO_TYPE_OBJECT clazz:[Finding_SellerInfo class]];
    [map setObject:ps forKey:@"sellerInfo"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"shippingInfo" propertyName:@"shippingInfo" type:PICO_TYPE_OBJECT clazz:[Finding_ShippingInfo class]];
    [map setObject:ps forKey:@"shippingInfo"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"sellingStatus" propertyName:@"sellingStatus" type:PICO_TYPE_OBJECT clazz:[Finding_SellingStatus class]];
    [map setObject:ps forKey:@"sellingStatus"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"listingInfo" propertyName:@"listingInfo" type:PICO_TYPE_OBJECT clazz:[Finding_ListingInfo class]];
    [map setObject:ps forKey:@"listingInfo"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"returnsAccepted" propertyName:@"returnsAccepted" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"returnsAccepted"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"galleryPlusPictureURL" propertyName:@"galleryPlusPictureURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"galleryPlusPictureURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"compatibility" propertyName:@"compatibility" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"compatibility"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"distance" propertyName:@"distance" type:PICO_TYPE_OBJECT clazz:[Finding_Distance class]];
    [map setObject:ps forKey:@"distance"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"condition" propertyName:@"condition" type:PICO_TYPE_OBJECT clazz:[Finding_Condition class]];
    [map setObject:ps forKey:@"condition"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"isMultiVariationListing" propertyName:@"isMultiVariationListing" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"isMultiVariationListing"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"discountPriceInfo" propertyName:@"discountPriceInfo" type:PICO_TYPE_OBJECT clazz:[Finding_DiscountPriceInfo class]];
    [map setObject:ps forKey:@"discountPriceInfo"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"pictureURLSuperSize" propertyName:@"pictureURLSuperSize" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"pictureURLSuperSize"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"pictureURLLarge" propertyName:@"pictureURLLarge" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"pictureURLLarge"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"unitPrice" propertyName:@"unitPrice" type:PICO_TYPE_OBJECT clazz:[Finding_UnitPriceInfo class]];
    [map setObject:ps forKey:@"unitPrice"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"attribute" propertyName:@"attribute" type:PICO_TYPE_OBJECT clazz:[Finding_ItemAttribute class]];
    [map setObject:ps forKey:@"attribute"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"topRatedListing" propertyName:@"topRatedListing" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"topRatedListing"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"delimiter" propertyName:@"delimiter" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"delimiter"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"eekStatus" propertyName:@"eekStatus" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"eekStatus"];
    
    return map;
}




@end
