// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"



/**
 
 <b>As of October 2014, domains will be deprecated and "category" is used instead. </b>
 
 
 @ingroup FindingServicePortType
*/
@interface Finding_DomainFilter : NSObject <PicoBindable> {

@private
    NSMutableArray *_domainName;
    NSString *_delimiter;
    NSMutableArray *_any;

}


/**
 
     <b>As of October 2014, domains will be deprecated and "category" is used instead. </b>
 
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *domainName;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *delimiter;

/**
 (public property)
 
 entry type : PicoAnyElement, wrapper for primitive anyelement
*/

@property (nonatomic, strong) NSMutableArray *any;


@end
