// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Finding_BaseFindingServiceResponse.h"


@class Finding_AspectHistogramContainer;
@class Finding_ConditionHistogramContainer;

/**
 
 Response container for the findItemsByProduct call.
 
 
 @ingroup FindingServicePortType
*/
@interface Finding_FindItemsByProductResponse : Finding_BaseFindingServiceResponse {

@private
    Finding_AspectHistogramContainer *_aspectHistogramContainer;
    Finding_ConditionHistogramContainer *_conditionHistogramContainer;

}


/**
 
 Response container for aspect histograms.
 
 
 type : class Finding_AspectHistogramContainer
*/
@property (nonatomic, strong) Finding_AspectHistogramContainer *aspectHistogramContainer;

/**
 
 Response container for condition histograms.<br>
 <br>
 Not returned when Condition is specified in itemFilter.
 That is, only returned when you have not yet narrowed
 your search based on specific conditions.<br>
 <br>
 Only returned when you search the eBay US site (as of
 February 2011). International items in US search results
 are included in the histogram counts.
 
 
 type : class Finding_ConditionHistogramContainer
*/
@property (nonatomic, strong) Finding_ConditionHistogramContainer *conditionHistogramContainer;


@end
