// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Finding_BaseServiceResponse.h"


@class Finding_ExtensionType;
@class Finding_CategoryHistogramContainer;
@class Finding_AspectHistogramContainer;
@class Finding_ConditionHistogramContainer;

/**
 
 Response container for the getHistogram call.
 
 
 @ingroup FindingServicePortType
*/
@interface Finding_GetHistogramsResponse : Finding_BaseServiceResponse {

@private
    Finding_CategoryHistogramContainer *_categoryHistogramContainer;
    Finding_AspectHistogramContainer *_aspectHistogramContainer;
    Finding_ConditionHistogramContainer *_conditionHistogramContainer;
    NSMutableArray *_extension;

}


/**
 
 Response container for category histograms. This container is
 returned only when the specified category has children categories.
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 Category histograms may not be available for some parent categories
 on the eBay Motors site.
 </span>
 
 
 type : class Finding_CategoryHistogramContainer
*/
@property (nonatomic, strong) Finding_CategoryHistogramContainer *categoryHistogramContainer;

/**
 
 Response container for aspect histograms. Aspect histograms are
 returned for categories only.
 
 
 type : class Finding_AspectHistogramContainer
*/
@property (nonatomic, strong) Finding_AspectHistogramContainer *aspectHistogramContainer;

/**
 
 Response container for condition histograms.
 Returned for leaf and parent categories.<br>
 <br>
 Only returned when you search the eBay US site (as of
 February 2011). International items in US search results
 are included in the histogram counts.
 
 
 type : class Finding_ConditionHistogramContainer
*/
@property (nonatomic, strong) Finding_ConditionHistogramContainer *conditionHistogramContainer;

/**
 
 Reserved for future use.
 
 
 entry type : class Finding_ExtensionType
*/

@property (nonatomic, strong) NSMutableArray *extension;


@end
