// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Finding_BaseServiceRequest.h"



/**
 
 Returns a a histogram for the supplied category or aspect.
 
 
 @ingroup FindingServicePortType
*/
@interface Finding_GetHistogramsRequest : Finding_BaseServiceRequest {

@private
    NSString *_categoryId;

}


/**
 
 Specifies the category from which you want to retrieve histogram
 information.
 <br><br>
 If a specified category ID doesn't match an existing category for the
 site, eBay returns an invalid-category error message. To determine
 valid categories, use the Shopping API <b
 class="con">GetCategoryInfo</b> call.
 
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *categoryId;


@end
