// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import "Finding_OutputSelectorType.h"

/**
 @file
 
 Values that specify additional information to be returned in the search results.
 
*/

/**
 
 Include information about the seller in the response.
 
*/
NSString *const Finding_OutputSelectorType_SELLER_INFO = @"SellerInfo";

/**
 
 Include information about the seller's eBay store in the response.
 
*/
NSString *const Finding_OutputSelectorType_STORE_INFO = @"StoreInfo";

/**
 
 Include a CategoryHistogram container with information about categories
 that match your search.
 
*/
NSString *const Finding_OutputSelectorType_CATEGORY_HISTOGRAM = @"CategoryHistogram";

/**
 
 Include an AspectHistogram container with information about aspects from
 the category that is most relevant to your search.
 </span>
 
*/
NSString *const Finding_OutputSelectorType_ASPECT_HISTOGRAM = @"AspectHistogram";

/**
 
 Include a ConditionHistogram container with the number of
 items found per condition (for example, how many items are new).
 This value has no effect when Condition is specified as
 an item filter. Supported for all eBay sites except US eBay Motors, India (IN), Malaysia
 (MY) and Philippines (PH).
 
*/
NSString *const Finding_OutputSelectorType_CONDITION_HISTOGRAM = @"ConditionHistogram";

/**
 
 Include the GalleryInfoContainer, which contains URLs for three thumbnail
 images of the item in different sizes: large, medium, and small.
 
*/
NSString *const Finding_OutputSelectorType_GALLERY_INFO = @"GalleryInfo";

/**
 
 Include a URL to a picture of the item that is 800x800 pixels in size.
 
*/
NSString *const Finding_OutputSelectorType_PICTURE_URL_SUPER_SIZE = @"PictureURLSuperSize";

/**
 
 Include a URL to a picture of the item that is 400x400 pixels in size.
 
*/
NSString *const Finding_OutputSelectorType_PICTURE_URL_LARGE = @"PictureURLLarge";

/**
 
 Include the unitPrice container with unit type and quantity information used for per-unit
 pricing (on eBay EU sites only).
 
*/
NSString *const Finding_OutputSelectorType_UNIT_PRICE_INFO = @"UnitPriceInfo";
