// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Finding_SellerInfo.h"

@implementation Finding_SellerInfo

@synthesize sellerUserName = _sellerUserName;
@synthesize feedbackScore = _feedbackScore;
@synthesize positiveFeedbackPercent = _positiveFeedbackPercent;
@synthesize feedbackRatingStar = _feedbackRatingStar;
@synthesize topRatedSeller = _topRatedSeller;
@synthesize delimiter = _delimiter;
@synthesize any = _any;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"sellerUserName" propertyName:@"sellerUserName" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"sellerUserName"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"feedbackScore" propertyName:@"feedbackScore" type:PICO_TYPE_LONG clazz:nil];
    [map setObject:ps forKey:@"feedbackScore"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"positiveFeedbackPercent" propertyName:@"positiveFeedbackPercent" type:PICO_TYPE_DOUBLE clazz:nil];
    [map setObject:ps forKey:@"positiveFeedbackPercent"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"feedbackRatingStar" propertyName:@"feedbackRatingStar" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"feedbackRatingStar"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"topRatedSeller" propertyName:@"topRatedSeller" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"topRatedSeller"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"delimiter" propertyName:@"delimiter" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"delimiter"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ANY_ELEMENT xmlName:@"any" propertyName:@"any" type:PICO_TYPE_ANYELEMENT clazz:nil];
    [map setObject:ps forKey:@"any"];
    
    return map;
}




@end
