// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"
#import "Finding_BaseFindingServiceResponse.h"


@class Finding_CategoryHistogramContainer;
@class Finding_AspectHistogramContainer;
@class Finding_ConditionHistogramContainer;

/**
 
 Response container for the findItemsByKeywords call.
 
 
 @ingroup FindingServicePortType
*/
@interface Finding_FindItemsByKeywordsResponse : Finding_BaseFindingServiceResponse {

@private
    Finding_CategoryHistogramContainer *_categoryHistogramContainer;
    Finding_AspectHistogramContainer *_aspectHistogramContainer;
    Finding_ConditionHistogramContainer *_conditionHistogramContainer;

}


/**
 
 Response container for category histograms. Only returned when one or
 more category histograms are returned. A category histogram is not
 returned if the search query returns no matching items.
 <br><br>
 <span class="tablenote"><strong>Note:</strong>
 When searching the eBay Motors site, category histograms may not be
 available for some parent categories. In these cases, aspect
 histograms should be used to refine search results. This behavior
 is consistent with eBay Motors site search behavior.
 </span>
 
 
 type : class Finding_CategoryHistogramContainer
*/
@property (nonatomic, strong) Finding_CategoryHistogramContainer *categoryHistogramContainer;

/**
 
 Response container for aspect histograms.
 
 
 type : class Finding_AspectHistogramContainer
*/
@property (nonatomic, strong) Finding_AspectHistogramContainer *aspectHistogramContainer;

/**
 
 Response container for condition histograms.<br>
 <br>
 Not returned when Condition is specified in itemFilter.
 That is, only returned when you have not yet narrowed
 your search based on specific conditions.<br>
 <br>
 Supported for all eBay sites except US eBay Motors,
 India (IN), Malaysia (MY) and Philippines (PH).
 International items that appear in search results
 are included in a site's histogram counts.
 
 
 type : class Finding_ConditionHistogramContainer
*/
@property (nonatomic, strong) Finding_ConditionHistogramContainer *conditionHistogramContainer;


@end
