// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class DecimalWithUnits;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface PackageDimensions : NSObject <PicoBindable> {

@private
    DecimalWithUnits *_height;
    DecimalWithUnits *_length;
    DecimalWithUnits *_weight;
    DecimalWithUnits *_width;

}


/**
 (public property)
 
 type : class DecimalWithUnits
*/
@property (nonatomic, strong) DecimalWithUnits *height;

/**
 (public property)
 
 type : class DecimalWithUnits
*/
@property (nonatomic, strong) DecimalWithUnits *length;

/**
 (public property)
 
 type : class DecimalWithUnits
*/
@property (nonatomic, strong) DecimalWithUnits *weight;

/**
 (public property)
 
 type : class DecimalWithUnits
*/
@property (nonatomic, strong) DecimalWithUnits *width;


@end
