// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "GenerateBarCode.h"
#import "BarCodeData.h"

@implementation GenerateBarCode

@synthesize barCodeParam = _barCodeParam;
@synthesize barCodeText = _barCodeText;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"GenerateBarCode" nsUri:@"http://www.webservicex.net/"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"BarCodeParam" propertyName:@"barCodeParam" type:PICO_TYPE_OBJECT clazz:[BarCodeData class]];
    [map setObject:ps forKey:@"barCodeParam"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"BarCodeText" propertyName:@"barCodeText" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"barCodeText"];
    
    return map;
}



-(void)dealloc {
    self.barCodeParam = nil;
    self.barCodeText = nil;
}

@end
