// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Forecast.h"
#import "POP.h"
#import "Temp.h"

@implementation Forecast

@synthesize date = _date;
@synthesize weatherID = _weatherID;
@synthesize desciption = _desciption;
@synthesize temperatures = _temperatures;
@synthesize probabilityOfPrecipiation = _probabilityOfPrecipiation;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Date" propertyName:@"date" type:PICO_TYPE_DATE clazz:nil];
    [map setObject:ps forKey:@"date"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"WeatherID" propertyName:@"weatherID" type:PICO_TYPE_SHORT clazz:nil];
    [map setObject:ps forKey:@"weatherID"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Desciption" propertyName:@"desciption" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"desciption"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Temperatures" propertyName:@"temperatures" type:PICO_TYPE_OBJECT clazz:[Temp class]];
    [map setObject:ps forKey:@"temperatures"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ProbabilityOfPrecipiation" propertyName:@"probabilityOfPrecipiation" type:PICO_TYPE_OBJECT clazz:[POP class]];
    [map setObject:ps forKey:@"probabilityOfPrecipiation"];
    
    return map;
}

@end
