// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Error.h"

@implementation Error

@synthesize code = _code;
@synthesize message = _message;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Code" propertyName:@"code" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"code"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Message" propertyName:@"message" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"message"];
    
    return map;
}




@end
