// Generated by wsdl compiler for ios/objective-c
// DO NOT CHANGE!


#import <Foundation/Foundation.h>
#import "PicoXMLClient.h"
#import "GetWeatherInformationResponse.h"
#import "GetCityForecastByZIP.h"
#import "GetCityWeatherByZIPResponse.h"
#import "GetWeatherInformation.h"
#import "GetCityWeatherByZIP.h"
#import "GetCityForecastByZIPResponse.h"


/**
 This class is the XML client to the WeatherSoap Web Service.
*/ 
@interface WeatherSoap_XMLClient : PicoXMLClient {

}

/**
 Gets Information for each WeatherID
*/
-(void)getWeatherInformation:(GetWeatherInformation *) requestObject 
      success:(void (^)(GetWeatherInformationResponse *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 Allows you to get your City Forecast Over the Next 7 Days, which is updated hourly. U.S. Only
*/
-(void)getCityForecastByZIP:(GetCityForecastByZIP *) requestObject 
      success:(void (^)(GetCityForecastByZIPResponse *responseObject))success
      failure:(void (^)(NSError *error))failure;

/**
 Allows you to get your City's Weather, which is updated hourly. U.S. Only
*/
-(void)getCityWeatherByZIP:(GetCityWeatherByZIP *) requestObject 
      success:(void (^)(GetCityWeatherByZIPResponse *responseObject))success
      failure:(void (^)(NSError *error))failure;


@end