// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

/**
   Common header file
*/

#import "GenerateBarCode.h"
#import "BarCodeData.h"
#import "GenerateBarCodeResponse.h"

#import "BarcodeType.h"
#import "ShowTextPosition.h"
#import "ImageFormats.h"
#import "CheckSumMethod.h"
#import "BarcodeOption.h"
