// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class SOAP12Subcode;

/**
 (public class)
 
*/
@interface SOAP12Faultcode : NSObject <PicoBindable> {

@private
    NSString *_value;
    SOAP12Subcode *_subcode;

}


/**
 (public property)
 
 type: string constant in SOAP12FaultcodeEnum.h
*/
@property (nonatomic, strong) NSString *value;

/**
 (public property)
 
 type : class SOAP12Subcode
*/
@property (nonatomic, strong) SOAP12Subcode *subcode;


@end
