// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "BrowseNodes.h"
#import "Request.h"
#import "BrowseNode.h"

@implementation BrowseNodes

@synthesize request = _request;
@synthesize browseNode = _browseNode;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"BrowseNodes" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Request" propertyName:@"request" type:PICO_TYPE_OBJECT clazz:[Request class]];
    [map setObject:ps forKey:@"request"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"BrowseNode" propertyName:@"browseNode" type:PICO_TYPE_OBJECT clazz:[BrowseNode class]];
    [map setObject:ps forKey:@"browseNode"];
    
    return map;
}




@end
