// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Cart.h"
#import "TopSellers.h"
#import "Price.h"
#import "Request.h"
#import "NewReleases.h"
#import "OtherCategoriesSimilarProducts.h"
#import "CartItems.h"
#import "SavedForLaterItems.h"
#import "SimilarViewedProducts.h"
#import "SimilarProducts.h"

@implementation Cart

@synthesize request = _request;
@synthesize cartId = _cartId;
@synthesize hmac = _hmac;
@synthesize urlEncodedHMAC = _urlEncodedHMAC;
@synthesize purchaseURL = _purchaseURL;
@synthesize mobileCartURL = _mobileCartURL;
@synthesize subTotal = _subTotal;
@synthesize cartItems = _cartItems;
@synthesize savedForLaterItems = _savedForLaterItems;
@synthesize similarProducts = _similarProducts;
@synthesize topSellers = _topSellers;
@synthesize amazonNewReleases = _newReleases;
@synthesize similarViewedProducts = _similarViewedProducts;
@synthesize otherCategoriesSimilarProducts = _otherCategoriesSimilarProducts;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"Cart" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Request" propertyName:@"request" type:PICO_TYPE_OBJECT clazz:[Request class]];
    [map setObject:ps forKey:@"request"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CartId" propertyName:@"cartId" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"cartId"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"HMAC" propertyName:@"hmac" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"hmac"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"URLEncodedHMAC" propertyName:@"urlEncodedHMAC" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"urlEncodedHMAC"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"PurchaseURL" propertyName:@"purchaseURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"purchaseURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MobileCartURL" propertyName:@"mobileCartURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"mobileCartURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SubTotal" propertyName:@"subTotal" type:PICO_TYPE_OBJECT clazz:[Price class]];
    [map setObject:ps forKey:@"subTotal"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CartItems" propertyName:@"cartItems" type:PICO_TYPE_OBJECT clazz:[CartItems class]];
    [map setObject:ps forKey:@"cartItems"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SavedForLaterItems" propertyName:@"savedForLaterItems" type:PICO_TYPE_OBJECT clazz:[SavedForLaterItems class]];
    [map setObject:ps forKey:@"savedForLaterItems"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SimilarProducts" propertyName:@"similarProducts" type:PICO_TYPE_OBJECT clazz:[SimilarProducts class]];
    [map setObject:ps forKey:@"similarProducts"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TopSellers" propertyName:@"topSellers" type:PICO_TYPE_OBJECT clazz:[TopSellers class]];
    [map setObject:ps forKey:@"topSellers"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"NewReleases" propertyName:@"newReleases" type:PICO_TYPE_OBJECT clazz:[NewReleases class]];
    [map setObject:ps forKey:@"newReleases"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SimilarViewedProducts" propertyName:@"similarViewedProducts" type:PICO_TYPE_OBJECT clazz:[SimilarViewedProducts class]];
    [map setObject:ps forKey:@"similarViewedProducts"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"OtherCategoriesSimilarProducts" propertyName:@"otherCategoriesSimilarProducts" type:PICO_TYPE_OBJECT clazz:[OtherCategoriesSimilarProducts class]];
    [map setObject:ps forKey:@"otherCategoriesSimilarProducts"];
    
    return map;
}




@end
