// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Price;
@class MetaData;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface CartItem : NSObject <PicoBindable> {

@private
    NSString *_cartItemId;
    NSString *_asin;
    NSString *_sellerNickname;
    NSString *_quantity;
    NSString *_title;
    NSString *_productGroup;
    MetaData *_metaData;
    Price *_price;
    Price *_itemTotal;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *cartItemId;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *asin;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *sellerNickname;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *quantity;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *title;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *productGroup;

/**
 (public property)
 
 type : class MetaData
*/
@property (nonatomic, strong) MetaData *metaData;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *price;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *itemTotal;


@end
