// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "CustomerReviews.h"

@implementation CustomerReviews

@synthesize iFrameURL = _iFrameURL;
@synthesize hasReviews = _hasReviews;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"CustomerReviews" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IFrameURL" propertyName:@"iFrameURL" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"iFrameURL"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"HasReviews" propertyName:@"hasReviews" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"hasReviews"];
    
    return map;
}




@end
