// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "EditorialReview.h"

@implementation EditorialReview

@synthesize source = _source;
@synthesize content = _content;
@synthesize isLinkSuppressed = _isLinkSuppressed;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"EditorialReview" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Source" propertyName:@"source" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"source"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Content" propertyName:@"content" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"content"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsLinkSuppressed" propertyName:@"isLinkSuppressed" type:PICO_TYPE_BOOL clazz:nil];
    [map setObject:ps forKey:@"isLinkSuppressed"];
    
    return map;
}




@end
