// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Image.h"
#import "DecimalWithUnits.h"

@implementation Image

@synthesize url = _url;
@synthesize height = _height;
@synthesize width = _width;
@synthesize isVerified = _isVerified;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"URL" propertyName:@"url" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"url"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Height" propertyName:@"height" type:PICO_TYPE_OBJECT clazz:[DecimalWithUnits class]];
    [map setObject:ps forKey:@"height"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"Width" propertyName:@"width" type:PICO_TYPE_OBJECT clazz:[DecimalWithUnits class]];
    [map setObject:ps forKey:@"width"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"IsVerified" propertyName:@"isVerified" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"isVerified"];
    
    return map;
}




@end
