// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "ImageSet.h"
#import "Image.h"

@implementation ImageSet

@synthesize swatchImage = _swatchImage;
@synthesize smallImage = _smallImage;
@synthesize thumbnailImage = _thumbnailImage;
@synthesize tinyImage = _tinyImage;
@synthesize mediumImage = _mediumImage;
@synthesize largeImage = _largeImage;
@synthesize category = _category;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"ImageSet" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SwatchImage" propertyName:@"swatchImage" type:PICO_TYPE_OBJECT clazz:[Image class]];
    [map setObject:ps forKey:@"swatchImage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"SmallImage" propertyName:@"smallImage" type:PICO_TYPE_OBJECT clazz:[Image class]];
    [map setObject:ps forKey:@"smallImage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"ThumbnailImage" propertyName:@"thumbnailImage" type:PICO_TYPE_OBJECT clazz:[Image class]];
    [map setObject:ps forKey:@"thumbnailImage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"TinyImage" propertyName:@"tinyImage" type:PICO_TYPE_OBJECT clazz:[Image class]];
    [map setObject:ps forKey:@"tinyImage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"MediumImage" propertyName:@"mediumImage" type:PICO_TYPE_OBJECT clazz:[Image class]];
    [map setObject:ps forKey:@"mediumImage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"LargeImage" propertyName:@"largeImage" type:PICO_TYPE_OBJECT clazz:[Image class]];
    [map setObject:ps forKey:@"largeImage"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ATTRIBUTE xmlName:@"Category" propertyName:@"category" type:PICO_TYPE_STRING clazz:nil];
    [map setObject:ps forKey:@"category"];
    
    return map;
}




@end
