// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class BrowseNodes;
@class Tracks;
@class EditorialReviews;
@class ItemLinks;
@class Variations;
@class AlternateVersions;
@class Offers;
@class Image;
@class VariationAttributes;
@class Errors;
@class Accessories;
@class VariationSummary;
@class OfferSummary;
@class ImageSets;
@class ItemAttributes;
@class Collections;
@class CustomerReviews;
@class RelatedItems;
@class Subjects;
@class SimilarProducts;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface Item : NSObject <PicoBindable> {

@private
    NSString *_asin;
    NSString *_parentASIN;
    Errors *_errors;
    NSString *_detailPageURL;
    ItemLinks *_itemLinks;
    NSString *_salesRank;
    Image *_smallImage;
    Image *_mediumImage;
    Image *_largeImage;
    NSMutableArray *_imageSets;
    ItemAttributes *_itemAttributes;
    VariationAttributes *_variationAttributes;
    NSMutableArray *_relatedItems;
    Collections *_collections;
    Subjects *_subjects;
    OfferSummary *_offerSummary;
    Offers *_offers;
    VariationSummary *_variationSummary;
    Variations *_variations;
    CustomerReviews *_customerReviews;
    EditorialReviews *_editorialReviews;
    SimilarProducts *_similarProducts;
    Accessories *_accessories;
    Tracks *_tracks;
    BrowseNodes *_browseNodes;
    AlternateVersions *_alternateVersions;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *asin;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *parentASIN;

/**
 (public property)
 
 type : class Errors
*/
@property (nonatomic, strong) Errors *errors;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *detailPageURL;

/**
 (public property)
 
 type : class ItemLinks
*/
@property (nonatomic, strong) ItemLinks *itemLinks;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *salesRank;

/**
 (public property)
 
 type : class Image
*/
@property (nonatomic, strong) Image *smallImage;

/**
 (public property)
 
 type : class Image
*/
@property (nonatomic, strong) Image *mediumImage;

/**
 (public property)
 
 type : class Image
*/
@property (nonatomic, strong) Image *largeImage;

/**
 (public property)
 
 entry type : class ImageSets
*/

@property (nonatomic, strong) NSMutableArray *imageSets;

/**
 (public property)
 
 type : class ItemAttributes
*/
@property (nonatomic, strong) ItemAttributes *itemAttributes;

/**
 (public property)
 
 type : class VariationAttributes
*/
@property (nonatomic, strong) VariationAttributes *variationAttributes;

/**
 (public property)
 
 entry type : class RelatedItems
*/

@property (nonatomic, strong) NSMutableArray *relatedItems;

/**
 (public property)
 
 type : class Collections
*/
@property (nonatomic, strong) Collections *collections;

/**
 (public property)
 
 type : class Subjects
*/
@property (nonatomic, strong) Subjects *subjects;

/**
 (public property)
 
 type : class OfferSummary
*/
@property (nonatomic, strong) OfferSummary *offerSummary;

/**
 (public property)
 
 type : class Offers
*/
@property (nonatomic, strong) Offers *offers;

/**
 (public property)
 
 type : class VariationSummary
*/
@property (nonatomic, strong) VariationSummary *variationSummary;

/**
 (public property)
 
 type : class Variations
*/
@property (nonatomic, strong) Variations *variations;

/**
 (public property)
 
 type : class CustomerReviews
*/
@property (nonatomic, strong) CustomerReviews *customerReviews;

/**
 (public property)
 
 type : class EditorialReviews
*/
@property (nonatomic, strong) EditorialReviews *editorialReviews;

/**
 (public property)
 
 type : class SimilarProducts
*/
@property (nonatomic, strong) SimilarProducts *similarProducts;

/**
 (public property)
 
 type : class Accessories
*/
@property (nonatomic, strong) Accessories *accessories;

/**
 (public property)
 
 type : class Tracks
*/
@property (nonatomic, strong) Tracks *tracks;

/**
 (public property)
 
 type : class BrowseNodes
*/
@property (nonatomic, strong) BrowseNodes *browseNodes;

/**
 (public property)
 
 type : class AlternateVersions
*/
@property (nonatomic, strong) AlternateVersions *alternateVersions;


@end
