// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Price;
@class PackageDimensions;
@class ItemDimensions;
@class NonNegativeIntegerWithUnits;
@class EANList;
@class Languages;
@class DecimalWithUnits;
@class Creator;
@class CatalogNumberList;
@class UPCList;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface ItemAttributes : NSObject <PicoBindable> {

@private
    NSMutableArray *_actor;
    NSMutableArray *_artist;
    NSString *_aspectRatio;
    NSString *_audienceRating;
    NSMutableArray *_audioFormat;
    NSMutableArray *_author;
    NSString *_binding;
    NSString *_brand;
    CatalogNumberList *_catalogNumberList;
    NSMutableArray *_category;
    NSString *_ceroAgeRating;
    NSString *_clothingSize;
    NSString *_color;
    NSMutableArray *_creator;
    NSString *_department;
    NSMutableArray *_director;
    NSString *_ean;
    EANList *_eanList;
    NSString *_edition;
    NSMutableArray *_eisbn;
    NSString *_episodeSequence;
    NSString *_esrbAgeRating;
    NSMutableArray *_feature;
    NSMutableArray *_format;
    NSString *_genre;
    NSString *_hardwarePlatform;
    NSString *_hazardousMaterialType;
    NSNumber *_isAdultProduct;
    NSNumber *_isAutographed;
    NSString *_isbn;
    NSNumber *_isEligibleForTradeIn;
    NSNumber *_isMemorabilia;
    NSString *_issuesPerYear;
    ItemDimensions *_itemDimensions;
    NSString *_itemPartNumber;
    NSString *_label;
    Languages *_languages;
    NSString *_legalDisclaimer;
    Price *_listPrice;
    NSString *_magazineType;
    NSString *_manufacturer;
    DecimalWithUnits *_manufacturerMaximumAge;
    DecimalWithUnits *_manufacturerMinimumAge;
    NSString *_manufacturerPartsWarrantyDescription;
    NSString *_mediaType;
    NSString *_model;
    NSNumber *_modelYear;
    NSString *_mpn;
    NSNumber *_numberOfDiscs;
    NSNumber *_numberOfIssues;
    NSNumber *_numberOfItems;
    NSNumber *_numberOfPages;
    NSNumber *_numberOfTracks;
    NSString *_operatingSystem;
    PackageDimensions *_packageDimensions;
    NSNumber *_packageQuantity;
    NSString *_partNumber;
    NSMutableArray *_pictureFormat;
    NSMutableArray *_platform;
    NSString *_productGroup;
    NSString *_productTypeName;
    NSString *_productTypeSubcategory;
    NSString *_publicationDate;
    NSString *_publisher;
    NSString *_regionCode;
    NSString *_releaseDate;
    DecimalWithUnits *_runningTime;
    NSString *_seikodoProductCode;
    NSString *_size;
    NSString *_sku;
    NSString *_studio;
    NonNegativeIntegerWithUnits *_subscriptionLength;
    NSString *_title;
    NSString *_trackSequence;
    Price *_tradeInValue;
    NSString *_upc;
    UPCList *_upcList;
    NSString *_warranty;
    Price *_weeeTaxValue;

}


/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *actor;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *artist;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *aspectRatio;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *audienceRating;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *audioFormat;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *author;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *binding;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *brand;

/**
 (public property)
 
 type : class CatalogNumberList
*/
@property (nonatomic, strong) CatalogNumberList *catalogNumberList;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *category;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *ceroAgeRating;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *clothingSize;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *color;

/**
 (public property)
 
 entry type : class Creator
*/

@property (nonatomic, strong) NSMutableArray *creator;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *department;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *director;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *ean;

/**
 (public property)
 
 type : class EANList
*/
@property (nonatomic, strong) EANList *eanList;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *edition;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *eisbn;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *episodeSequence;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *esrbAgeRating;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *feature;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *format;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *genre;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *hardwarePlatform;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *hazardousMaterialType;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, strong) NSNumber *isAdultProduct;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, strong) NSNumber *isAutographed;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *isbn;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, strong) NSNumber *isEligibleForTradeIn;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, strong) NSNumber *isMemorabilia;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *issuesPerYear;

/**
 (public property)
 
 type : class ItemDimensions
*/
@property (nonatomic, strong) ItemDimensions *itemDimensions;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *itemPartNumber;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *label;

/**
 (public property)
 
 type : class Languages
*/
@property (nonatomic, strong) Languages *languages;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *legalDisclaimer;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *listPrice;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *magazineType;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *manufacturer;

/**
 (public property)
 
 type : class DecimalWithUnits
*/
@property (nonatomic, strong) DecimalWithUnits *manufacturerMaximumAge;

/**
 (public property)
 
 type : class DecimalWithUnits
*/
@property (nonatomic, strong) DecimalWithUnits *manufacturerMinimumAge;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *manufacturerPartsWarrantyDescription;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *mediaType;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *model;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *modelYear;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *mpn;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *numberOfDiscs;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *numberOfIssues;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *numberOfItems;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *numberOfPages;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *numberOfTracks;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *operatingSystem;

/**
 (public property)
 
 type : class PackageDimensions
*/
@property (nonatomic, strong) PackageDimensions *packageDimensions;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *packageQuantity;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *partNumber;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *pictureFormat;

/**
 (public property)
 
 entry type : NSString, wrapper for primitive string
*/

@property (nonatomic, strong) NSMutableArray *platform;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *productGroup;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *productTypeName;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *productTypeSubcategory;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *publicationDate;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *publisher;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *regionCode;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *releaseDate;

/**
 (public property)
 
 type : class DecimalWithUnits
*/
@property (nonatomic, strong) DecimalWithUnits *runningTime;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *seikodoProductCode;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *size;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *sku;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *studio;

/**
 (public property)
 
 type : class NonNegativeIntegerWithUnits
*/
@property (nonatomic, strong) NonNegativeIntegerWithUnits *subscriptionLength;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *title;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *trackSequence;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *tradeInValue;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *upc;

/**
 (public property)
 
 type : class UPCList
*/
@property (nonatomic, strong) UPCList *upcList;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *warranty;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *weeeTaxValue;


@end
