// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Price;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface LoyaltyPoints : NSObject <PicoBindable> {

@private
    NSNumber *_points;
    Price *_typicalRedemptionValue;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *points;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *typicalRedemptionValue;


@end
