// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Price;
@class AvailabilityAttributes;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface OfferListing : NSObject <PicoBindable> {

@private
    NSString *_offerListingId;
    Price *_price;
    Price *_salePrice;
    Price *_amountSaved;
    NSNumber *_percentageSaved;
    NSString *_availability;
    AvailabilityAttributes *_availabilityAttributes;
    NSNumber *_isEligibleForSuperSaverShipping;
    NSNumber *_isEligibleForPrime;

}


/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *offerListingId;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *price;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *salePrice;

/**
 (public property)
 
 type : class Price
*/
@property (nonatomic, strong) Price *amountSaved;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *percentageSaved;

/**
 (public property)
 
 type : NSString, wrapper for primitive string
*/
@property (nonatomic, strong) NSString *availability;

/**
 (public property)
 
 type : class AvailabilityAttributes
*/
@property (nonatomic, strong) AvailabilityAttributes *availabilityAttributes;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, strong) NSNumber *isEligibleForSuperSaverShipping;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive bool
*/
@property (nonatomic, strong) NSNumber *isEligibleForPrime;


@end
