// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class OfferListing;
@class Merchant;
@class Promotions;
@class OfferAttributes;
@class LoyaltyPoints;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface Offer : NSObject <PicoBindable> {

@private
    Merchant *_merchant;
    OfferAttributes *_offerAttributes;
    NSMutableArray *_offerListing;
    LoyaltyPoints *_loyaltyPoints;
    Promotions *_promotions;

}


/**
 (public property)
 
 type : class Merchant
*/
@property (nonatomic, strong) Merchant *merchant;

/**
 (public property)
 
 type : class OfferAttributes
*/
@property (nonatomic, strong) OfferAttributes *offerAttributes;

/**
 (public property)
 
 entry type : class OfferListing
*/

@property (nonatomic, strong) NSMutableArray *offerListing;

/**
 (public property)
 
 type : class LoyaltyPoints
*/
@property (nonatomic, strong) LoyaltyPoints *loyaltyPoints;

/**
 (public property)
 
 type : class Promotions
*/
@property (nonatomic, strong) Promotions *promotions;


@end
