// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "OtherCategoriesSimilarProducts.h"
#import "OtherCategoriesSimilarProduct.h"

@implementation OtherCategoriesSimilarProducts

@synthesize otherCategoriesSimilarProduct = _otherCategoriesSimilarProduct;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    PicoClassSchema *cs = [[PicoClassSchema alloc] initWithXmlName:@"OtherCategoriesSimilarProducts" nsUri:@"http://webservices.amazon.com/AWSECommerceService/2011-08-01"];
    return cs;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"OtherCategoriesSimilarProduct" propertyName:@"otherCategoriesSimilarProduct" type:PICO_TYPE_OBJECT clazz:[OtherCategoriesSimilarProduct class]];
    [map setObject:ps forKey:@"otherCategoriesSimilarProduct"];
    
    return map;
}




@end
