// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "PicoClassSchema.h"
#import "PicoPropertySchema.h"
#import "PicoConstants.h"
#import "PicoBindable.h"


@class Item;
@class VariationDimensions;

/**
 (public class)
 
 @ingroup AWSECommerceServicePortType
*/
@interface Variations : NSObject <PicoBindable> {

@private
    NSNumber *_totalVariations;
    NSNumber *_totalVariationPages;
    VariationDimensions *_variationDimensions;
    NSMutableArray *_item;

}


/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *totalVariations;

/**
 (public property)
 
 type : NSNumber, wrapper for primitive long
*/
@property (nonatomic, strong) NSNumber *totalVariationPages;

/**
 (public property)
 
 type : class VariationDimensions
*/
@property (nonatomic, strong) VariationDimensions *variationDimensions;

/**
 (public property)
 
 entry type : class Item
*/

@property (nonatomic, strong) NSMutableArray *item;


@end
