// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <Foundation/Foundation.h>
#import "OrderedDictionary.h"
#import "Collection.h"
#import "CollectionItem.h"
#import "CollectionSummary.h"
#import "CollectionParent.h"

@implementation Collection

@synthesize collectionSummary = _collectionSummary;
@synthesize collectionParent = _collectionParent;
@synthesize collectionItem = _collectionItem;

// class meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(PicoClassSchema *)getClassMetaData {
    return nil;
}

// property meta-data method
// note: this method is only for internal use, DO NOT CHANGE!
+(NSMutableDictionary *)getPropertyMetaData {
    NSMutableDictionary *map = [OrderedDictionary dictionary];
    
    PicoPropertySchema *ps = nil;
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CollectionSummary" propertyName:@"collectionSummary" type:PICO_TYPE_OBJECT clazz:[CollectionSummary class]];
    [map setObject:ps forKey:@"collectionSummary"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT xmlName:@"CollectionParent" propertyName:@"collectionParent" type:PICO_TYPE_OBJECT clazz:[CollectionParent class]];
    [map setObject:ps forKey:@"collectionParent"];
    ps = [[PicoPropertySchema alloc] initWithKind:PICO_KIND_ELEMENT_ARRAY xmlName:@"CollectionItem" propertyName:@"collectionItem" type:PICO_TYPE_OBJECT clazz:[CollectionItem class]];
    [map setObject:ps forKey:@"collectionItem"];
    
    return map;
}




@end
