// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

/**
   Common header file
*/

#import "ForecastReturn.h"
#import "GetCityForecastByZIPResponse.h"
#import "GetCityWeatherByZIPResponse.h"
#import "WeatherReturn.h"
#import "GetWeatherInformation.h"
#import "Forecast.h"
#import "GetCityWeatherByZIP.h"
#import "WeatherDescription.h"
#import "POP.h"
#import "ArrayOfWeatherDescription.h"
#import "Temp.h"
#import "GetCityForecastByZIP.h"
#import "GetWeatherInformationResponse.h"
#import "ArrayOfForecast.h"

